

---


### {{question_text}}


---


Item ID: {{item_id}}

Way the question was delivered: {{question_type}}

Type of data: {{result_type}}



```{r, echo = FALSE}
### This is a simple skip logic check
### If this is a conditional question, print out parent item_id and parent question text

# Get current question ID
item_id <- substring("{{item_id}}", 6)


# Change Conditional Child Item ID column to character to make searching easy
blockMap$Conditional.Child.Item.ID <- as.character(blockMap$Conditional.Child.Item.ID)

# Check if Item ID is in conditional column....
## If so, display parent info
if (item_id %in% blockMap$Conditional.Child.Item.ID) {
  parent_row <- subset(blockMap, Conditional.Child.Item.ID == item_id)
  parent_text <- parent_row$Question.Text
  parent_itemID <- parent_row$Item.ID
  cat("This question is only delivered if participant answered question ", parent_itemID, ": ", parent_text)
}




##### I thought the child listed the parent not the other way around
##### This will essentially give you the same in reverse

#if (!is.na(blockMap$Conditional.Child.Item.ID[blockMap$Question.ID == "{{question_id}}"])) {
#  Conditional_itemID <- blockMap$Conditional.Child.Item.ID[blockMap$Question.ID == "{{question_id}}"]
#  Conditional_text <- blockMap$Question.Text[blockMap$Item.ID == Conditional_itemID]
#  cat("This question is only delivered if participant answered question ", Conditional_itemID, ": ", Conditional_text)
#}


```


```{r, echo = FALSE}
###################################################
### Missingness
####################################################
# This displays the count of missingness for people who actually recieved the item (i.e.... out of the 100 people it was delivered to, 50 responded to this question)
####################################################
#
# If skip logic exists, display the amount it was delivered to, otherwise list count
#
####################################################

## 1.) Calculate values

  ## Get the count of the number of parent_itemID rows in the data where User.Response does not equal NA
  
  ### Check if parent_itemID exists
  if (exists("parent_itemID") == T) {
    
    ## If it exists.... Grab count of people who answered the PARENT question
    
    n_delivered_to <- length(thisData[thisData$Item == parent_itemID & !is.na(thisData$User.Response), ])
    
  } else {
    
    ## Grab the count of people who answered the CURRENT question
    n_delivered_to <- length(thisData[thisData$Item == item_id, ])
  }


  ## Get the number of people who answered the current survey question
  n <- length(thisData[thisData$Item == item_id & !is.na(thisData$User.Response), ])

  ## Calculate percentage
  if (n_delivered_to > 0) {
  percentage <- round((n / n_delivered_to) * 100, 1)
  } else {
    percentage <- NA
  }

  
  
## 2.) Print out the results
  
  # If this is a skip logic question, display special type of missingness....
    report <- if (is.na(percentage)) {
      
      # If delivered to no one....
      paste0("This question was not delivered to any participants")
   
    
      # If delivered to some....  
      } else if (item_id %in% blockMap$Conditional.Child.Item.ID) {
      paste0("out of the ", n_delivered_to, " people this question was delivered to, ", n, " responded to this question... or... ", percentage, "%")
  
        
      # If delivered to everyone.... 
      } else {
       paste0("n = ", n, ", ", percentage, "%")
    }

    
  # Print out missingness report
  print(report)

```



