

---


### {{question_text}}


---


Item ID: {{item_id}}

Way the question was delivered: {{question_type}}

Type of data: {{result_type}}


```{r, echo = FALSE}
### This is a simple skip logic check
### If this is a conditional question, print out parent item_id and parent question text

# Get current question ID
item_id <- substring("{{item_id}}", 6)


# Change Conditional Child Item ID column to character to make searching easy
blockMap$Conditional.Child.Item.ID <- as.character(blockMap$Conditional.Child.Item.ID)

# Check if Item ID is in conditional column....
## If so, display parent info
if (item_id %in% blockMap$Conditional.Child.Item.ID) {
  parent_row <- subset(blockMap, Conditional.Child.Item.ID == item_id)
  parent_text <- parent_row$Question.Text
  parent_itemID <- parent_row$Item.ID
  cat("This question is only delivered if participant answered question ", parent_itemID, ": ", parent_text)
}




##### I thought the child listed the parent not the other way around
##### This will essentially give you the same in reverse

#if (!is.na(blockMap$Conditional.Child.Item.ID[blockMap$Question.ID == "{{question_id}}"])) {
#  Conditional_itemID <- blockMap$Conditional.Child.Item.ID[blockMap$Question.ID == "{{question_id}}"]
#  Conditional_text <- blockMap$Question.Text[blockMap$Item.ID == Conditional_itemID]
#  cat("This question is only delivered if participant answered question ", Conditional_itemID, ": ", Conditional_text)
#}


```
```{r, echo = FALSE}
# This is a simple check and display for the type of data
#if (!is.na(blockMap$Result.Type[blockMap$Question.ID == "{{question_id}}"])) {
#  cat("This data type is ", blockMap$Result.Type[blockMap$Question.ID == "{{question_id}}"])
#}

```

```{r, include = FALSE}
# I'm just hiding this 

##<details>
#<summary style="font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">Click to view frequency table</summary>
```
  
### Descriptives {.tabset}


#### Frequency Table

```{r, echo = FALSE}
# This is a simple frequency table
multiple_select_table <- table(unlist(strsplit(thisData$User.Response[thisData$Question.ID == "{{question_id}}"], ",")))

# This gives us the raw counts, ordered for each possible response
multiple_select_table <- multiple_select_table[order(as.numeric(names(multiple_select_table)))]

# These are the numeric values in the data
response_indicator <- names(multiple_select_table)

# Make each item a character that is N = *insert count*
n_counts <- sapply(multiple_select_table, function(x) paste0("N = ", x))




# Next pull out the name labels
response_labels <- list()

for (i in seq_along(names(multiple_select_table))) {
  val <- as.numeric(names(multiple_select_table)[i])
  response_labels[i] <- responseKey$definition[responseKey$value == val & responseKey$question == "{{question_id}}"]
}

# Unlist 
response_labels <- unlist(response_labels)
 
# Grab percentages
percentages <- round(100 * multiple_select_table / sum(multiple_select_table), 1)

# Make characters
percentages <- sapply(percentages, function(x) paste0(x, "%"))



# Combine all into a dataframe
df <- data.frame(Value = response_indicator, Label = response_labels, Counts = n_counts, Percentages = percentages)


library(kableExtra)

df %>%
  kbl() %>%
  kable_styling() %>% 
  column_spec(3, color = "darkgreen")

```




```{r, include=FALSE}
#</details>
```
