<!-- Header section -->

<div class = "header-shading">

### {{question_text}} <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  [{{item_id}}]
</div>


</div>



<!-- Body -->


<div class = "anchor">


**Way the question was delivered:** {{question_type}}

**Type of data:** {{result_type}}

```{r, echo = FALSE}
### This is a simple skip logic check
### If this is a conditional question, print out parent item_id and parent question text

# Get current question ID
item_id <- substring("{{item_id}}", 6)


# Change Conditional Child Item ID column to character to make searching easy
blockMap$Conditional.Child.Item.ID <- as.character(blockMap$Conditional.Child.Item.ID)

# Check if Item ID is in conditional column....
## If so, display parent info
if (item_id %in% blockMap$Conditional.Child.Item.ID) {
  parent_row <- subset(blockMap, Conditional.Child.Item.ID == item_id)
  parent_text <- parent_row$Question.Text
  parent_itemID <- parent_row$Item.ID
  cat("This question is only delivered if participant answered question ", parent_itemID, ": ", parent_text)
}




##### I thought the child listed the parent not the other way around
##### This will essentially give you the same in reverse

#if (!is.na(blockMap$Conditional.Child.Item.ID[blockMap$Question.ID == "{{question_id}}"])) {
#  Conditional_itemID <- blockMap$Conditional.Child.Item.ID[blockMap$Question.ID == "{{question_id}}"]
#  Conditional_text <- blockMap$Question.Text[blockMap$Item.ID == Conditional_itemID]
#  cat("This question is only delivered if participant answered question ", Conditional_itemID, ": ", Conditional_text)
#}


```

```{r, echo = FALSE}
thisBlock_df <- thisData[thisData$Question.ID == "{{question_id}}",]
thisBlock_df$User.Response <- as.numeric(thisBlock_df$User.Response)


# Grab basic descriptives
minimum_value <- round(min(thisBlock_df$User.Response, na.rm = TRUE), 2)
maximum_value <- round(max(thisBlock_df$User.Response, na.rm = TRUE), 2)
mean_value <- round(mean(thisBlock_df$User.Response, na.rm = TRUE), 2)
std_value <- round(sd(thisBlock_df$User.Response, na.rm = TRUE), 2)


paste0("Min = ", minimum_value, ", max = ", maximum_value, ", mean = ", mean_value, ", std = ", std_value)



```

```{r, echo = FALSE}
#################
# This is a basic histogram for continous data
######################
hist(thisBlock_df$User.Response, main = "Histogram", col ="#619CFF", border = "black", xlab = "0 - 100 Slider")


```


</div>
