# {{Question_Name}}: {{Question_Text}}

```{r populate, include=FALSE}
Question <- {{Question_Name}}
thisData <- {{tallData}} %>% filter(Question == Question)
```

[Image Missing]

This scale is a visual-analog sliding scale, with labels ranging from
{{lowlabel}}(value {{lowval}}) to {{highlabel}} ({{highval}}).

```{r CompletionRateCompute, echo=FALSE}
# Determine completion rates.
thisByDay <- thisData %>% group_by(dayOfStudy) %>% summarize(PctCompleted = 1-mean(Missing, na.rm=TRUE))
thisByID <- thisData %>% group_by(External.ID) %>% summarize(PctCompleted = 1-mean(Missing, na.rm=TRUE))
```

Overall completion rate is `r 1-mean(thisData$Missing, na.rm=TRUE)`.
```{r CompletionByDay}
ggplot(byDay, aes(x=dayOfStudy, y=PctCompleted)) + 
  geom_point(aes(color=cut(dailyPctComplete, c(0, 20, 40, 60, 80, 99, 100),
                           include.lowest = TRUE, right = TRUE))) + 
  geom_step(alpha=.25) +  # TODO: Maybe days with only root Qs?
  xlim(0,20) + facet_wrap(~YQ, scales = "free_y") + 
  labs(title="Total Completion Plot", 
       subtitle = "Character by status", x="Day of study", y="ID") +
  guides(col=guide_legend("Daily Completeness (%)"))
```

