---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
library(knitr)

```

# {{Survey_Name}}
```{r populate, include=FALSE}
thisData <- {thisData}
```


Survey block diagram:
```{r,include=FALSE}
blockMap <- {{blockMap}}
surveyInfo <- {{surveyInfo}}
responseKey <- {{responseKey}}
output_set <- {{output_set}}

```

[Image Missing]

This survey is delivered following
```{r CompletionRateCompute, echo=FALSE}
# Determine completion rates.
thisByDay <- thisData %>% group_by(dayOfStudy, YQ) %>% summarize(PctCompleted = 1-sum(Missing, na.rm=TRUE)/nrow())
thisByID <- thisData %>% group_by(External.ID) %>% summarize(PctCompleted = 1-mean(Missing, na.rm=TRUE), YQ=first(YQ))
```

Overall completion rate is `r 1-mean(thisData$Missing, na.rm=TRUE)`.
```{r CompletionByDay}
ggplot(thisByDay, aes(x=dayOfStudy, y=PctCompleted)) + 
  geom_col() + 
  geom_step(alpha=.25) +  # TODO: Maybe days with only root Qs?
  xlim(0,20) + facet_wrap(~YQ, scales = "free_y") + 
  labs(title="Total Completion Plot", 
       subtitle = "Character by status", x="Day of study", y="ID") +
  guides(col=guide_legend("Daily Completeness (%)"))
```

```{r echo=FALSE}


for(blockIdx in 1:nrow(blockMap)) {
  blockIdx <- blockIdx
  thisBlock <- blockMap[blockIdx,]
  if(thisBlock$Item.Type == "Question") {
    if(thisBlock$Question.Type.Display.Name == "Informational Fullscreen") {
      # Call Sub-page for This Question Type:
      attach(thisBlock)
      output_set <- paste(output_set,  knit_expand("Informational.Rmd"))
      detach(thisBlock)
    }
  }
}
```



`r knit(text=out)`

