---
title: "Recovery General Project Codebook"
author: "Ethan O. Kile"
date: "Codebook Generated 2025-10-02"
output: 
  html_document:
    keep_md: true
    toc: true
    toc_depth: 5
    css: styles.css
    includes:
      before_body: 
        - content-wrapper-start.html
        - logo.html
      after_body: 
        - content-wrapper-end.html
knitr:
  opts_chunk:
    message: false
    warning: false
params:
  title: "Default Title"
  authors: "Default Author"
---



<!-- Top of page button -->
<a href="#" id="backToTopBtn" title="Go to top">↑</a>


------------------------------------------------------------------------

# **Title Page**

------------------------------------------------------------------------

## Name of study

Recovery General Project Codebook

## Authors

Ethan O. Kile

## Desired graphic

![](images/rts.png)<!-- -->

## Funding source

This is a temp default funding source, please set

------------------------------------------------------------------------

# **Abstract Page**

------------------------------------------------------------------------

This is a temp default abstract, please set

------------------------------------------------------------------------

# **Effective Summary**

------------------------------------------------------------------------

This is a temp default summary, please set

------------------------------------------------------------------------

# **Variable List**

------------------------------------------------------------------------



 
## Daily Diary ID 470 <!-- Header section -->

<div class = "header-shading">

#### Did you receive support or help today?  SELECT ALL THAT APPLY:  (Scroll down for all responses) <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7605-anchor"> [Item 7605] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8176-anchor">
  <strong>Question ID</strong>: Question 8176
</div>

**Way the question was delivered:** Multiple Select

**Type of data:** integer

</div> 
<div class = "anchor">




<button 
  onclick="let e = document.getElementById('Question 8176');
           let arrow = document.getElementById('Question 8176_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8176_arrow">▼</span>
</button>

<div id="Question 8176" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Frequency Table

<table class="table" style="color: black; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> Value </th>
   <th style="text-align:left;"> Label </th>
   <th style="text-align:left;"> Counts </th>
   <th style="text-align:left;"> Percentages </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:left;"> Healthcare </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 82 </td>
   <td style="text-align:left;"> 6.6% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2 </td>
   <td style="text-align:left;"> Financial needs </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 61 </td>
   <td style="text-align:left;"> 4.9% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 3 </td>
   <td style="text-align:left;"> Food </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 104 </td>
   <td style="text-align:left;"> 8.3% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 4 </td>
   <td style="text-align:left;"> Shelter </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 71 </td>
   <td style="text-align:left;"> 5.7% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 5 </td>
   <td style="text-align:left;"> Transportation </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 85 </td>
   <td style="text-align:left;"> 6.8% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 6 </td>
   <td style="text-align:left;"> Other types of help to address your practical needs and physical wellbeing </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 218 </td>
   <td style="text-align:left;"> 17.5% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 7 </td>
   <td style="text-align:left;"> I did not receive any assistance, support, or help in any of these areas today. </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 628 </td>
   <td style="text-align:left;"> 50.3% </td>
  </tr>
</tbody>
</table>


#### Barplot

![](Codebook_files/figure-html/barplot-Multiple-Select-Question-8176-Item-7605-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 1042 / 1055

Missing = 13
Min = 0, Max = 5, Mean = 0.1, SD = 0.53
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = 1.05 


#### Screenshot



</div>


</div> <!-- Header section -->

<div class = "header-shading">

#### Whom did you receive this practical support from today? SELECT ALL THAT APPLY (Scroll down for all responses) <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7606-anchor"> [Item 7606] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8066-anchor">
  <strong>Question ID</strong>: Question 8066
</div>

**Way the question was delivered:** Multiple Select

**Type of data:** integer

</div> 
<div class = "anchor">




<button 
  onclick="let e = document.getElementById('Question 8066');
           let arrow = document.getElementById('Question 8066_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8066_arrow">▼</span>
</button>

<div id="Question 8066" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Frequency Table

<table class="table" style="color: black; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> Value </th>
   <th style="text-align:left;"> Label </th>
   <th style="text-align:left;"> Counts </th>
   <th style="text-align:left;"> Percentages </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:left;"> Certified Recovery Coach/specialist </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 19 </td>
   <td style="text-align:left;"> 2.8% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2 </td>
   <td style="text-align:left;"> Non-recovery friends and family </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 163 </td>
   <td style="text-align:left;"> 24.4% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 3 </td>
   <td style="text-align:left;"> Recovering friends and family </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 179 </td>
   <td style="text-align:left;"> 26.8% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 4 </td>
   <td style="text-align:left;"> My sponsor </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 50 </td>
   <td style="text-align:left;"> 7.5% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 5 </td>
   <td style="text-align:left;"> Therapist/counselor </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 30 </td>
   <td style="text-align:left;"> 4.5% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 6 </td>
   <td style="text-align:left;"> Community Resource – recovery center, mutual aid meeting, drug courts, educational setting, recovery housing,  treatment center, etc. </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 79 </td>
   <td style="text-align:left;"> 11.8% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 7 </td>
   <td style="text-align:left;"> Cultural/Spiritual/Faith-Based Institution </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 32 </td>
   <td style="text-align:left;"> 4.8% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 8 </td>
   <td style="text-align:left;"> Another source of support </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 115 </td>
   <td style="text-align:left;"> 17.2% </td>
  </tr>
</tbody>
</table>


#### Barplot

![](Codebook_files/figure-html/barplot-Multiple-Select-Question-8066-Item-7606-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 415 / 416

Missing = 1
Min = 0, Max = 1, Mean = 0.01, SD = 0.1
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = 1.32 


#### Screenshot



</div>


</div> <!-- Header section -->

<div class = "header-shading">

#### Did you receive emotional or interpersonal assistance, support, or help today in any of the following areas?  SELECT  ALL THAT APPLY  (Scroll down for all responses) <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7607-anchor"> [Item 7607] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8177-anchor">
  <strong>Question ID</strong>: Question 8177
</div>

**Way the question was delivered:** Multiple Select

**Type of data:** integer

</div> 
<div class = "anchor">




<button 
  onclick="let e = document.getElementById('Question 8177');
           let arrow = document.getElementById('Question 8177_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8177_arrow">▼</span>
</button>

<div id="Question 8177" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Frequency Table

<table class="table" style="color: black; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> Value </th>
   <th style="text-align:left;"> Label </th>
   <th style="text-align:left;"> Counts </th>
   <th style="text-align:left;"> Percentages </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:left;"> Dealing with personal relationships </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 275 </td>
   <td style="text-align:left;"> 17.6% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2 </td>
   <td style="text-align:left;"> Finding meaning and purpose in life </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 171 </td>
   <td style="text-align:left;"> 10.9% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 3 </td>
   <td style="text-align:left;"> Problem solving skills and tasks </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 261 </td>
   <td style="text-align:left;"> 16.7% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 4 </td>
   <td style="text-align:left;"> Recovery support </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 270 </td>
   <td style="text-align:left;"> 17.3% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 5 </td>
   <td style="text-align:left;"> Other interpersonal support not described above </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 176 </td>
   <td style="text-align:left;"> 11.3% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 6 </td>
   <td style="text-align:left;"> I did not receive any assistance, support, or help today. </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 409 </td>
   <td style="text-align:left;"> 26.2% </td>
  </tr>
</tbody>
</table>


#### Barplot

![](Codebook_files/figure-html/barplot-Multiple-Select-Question-8177-Item-7607-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 1047 / 1049

Missing = 2
Min = 0, Max = 1, Mean = 0.02, SD = 0.12
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = 1.15 


#### Screenshot



</div>


</div> <!-- Header section -->

<div class = "header-shading">

#### Whom did you receive this support from today?  SELECT ALL THAT APPLY  (Scroll down for all responses) <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7608-anchor"> [Item 7608] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8178-anchor">
  <strong>Question ID</strong>: Question 8178
</div>

**Way the question was delivered:** Multiple Select

**Type of data:** integer

</div> 
<div class = "anchor">




<button 
  onclick="let e = document.getElementById('Question 8178');
           let arrow = document.getElementById('Question 8178_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8178_arrow">▼</span>
</button>

<div id="Question 8178" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Frequency Table

<table class="table" style="color: black; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> Value </th>
   <th style="text-align:left;"> Label </th>
   <th style="text-align:left;"> Counts </th>
   <th style="text-align:left;"> Percentages </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:left;"> Certified Recovery Coach/specialist </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 33 </td>
   <td style="text-align:left;"> 3.1% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2 </td>
   <td style="text-align:left;"> Non-recovery friends and family </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 253 </td>
   <td style="text-align:left;"> 23.4% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 3 </td>
   <td style="text-align:left;"> Recovering friends and family </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 371 </td>
   <td style="text-align:left;"> 34.3% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 4 </td>
   <td style="text-align:left;"> My sponsor </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 117 </td>
   <td style="text-align:left;"> 10.8% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 5 </td>
   <td style="text-align:left;"> Therapist/counselor </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 55 </td>
   <td style="text-align:left;"> 5.1% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 6 </td>
   <td style="text-align:left;"> Community Resource – recovery center, mutual aid meeting, drug courts, educational setting, recovery housing, treatment center, etc. </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 80 </td>
   <td style="text-align:left;"> 7.4% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 7 </td>
   <td style="text-align:left;"> Cultural/Spiritual/Faith-Based Institution </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 53 </td>
   <td style="text-align:left;"> 4.9% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 8 </td>
   <td style="text-align:left;"> Another source of support </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 119 </td>
   <td style="text-align:left;"> 11% </td>
  </tr>
</tbody>
</table>


#### Barplot

![](Codebook_files/figure-html/barplot-Multiple-Select-Question-8178-Item-7608-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 637 / 638

Missing = 1
Min = 0, Max = 1, Mean = 0.01, SD = 0.09
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = 1.24 


#### Screenshot



</div>


</div> <!-- Header section -->

<div class = "header-shading">

#### How much time did you spend at a recovery community center (RCC) today? (Scroll down for all responses) <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7609-anchor"> [Item 7609] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8069-anchor">
  <strong>Question ID</strong>: Question 8069
</div>

**Way the question was delivered:** Multiple Choice

**Type of data:** integer

</div> 
<div class = "anchor">




<button 
  onclick="let e = document.getElementById('Question 8069');
           let arrow = document.getElementById('Question 8069_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8069_arrow">▼</span>
</button>

<div id="Question 8069" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Frequency Table

<table class="table" style="color: black; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> Value </th>
   <th style="text-align:left;"> Label </th>
   <th style="text-align:left;"> Counts </th>
   <th style="text-align:left;"> Percentages </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:left;"> I did not spend any time at a Recovery Center today </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 871 </td>
   <td style="text-align:left;"> 83% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2 </td>
   <td style="text-align:left;"> 1 – 30 minutes </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 28 </td>
   <td style="text-align:left;"> 2.7% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 3 </td>
   <td style="text-align:left;"> 30 – 60 minutes </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 29 </td>
   <td style="text-align:left;"> 2.8% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 4 </td>
   <td style="text-align:left;"> 1 – 2 hours </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 51 </td>
   <td style="text-align:left;"> 4.9% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 5 </td>
   <td style="text-align:left;"> 2 – 4 hours </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 20 </td>
   <td style="text-align:left;"> 1.9% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 6 </td>
   <td style="text-align:left;"> 4 – 6 hours </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 12 </td>
   <td style="text-align:left;"> 1.1% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 7 </td>
   <td style="text-align:left;"> More than 6 hours </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 39 </td>
   <td style="text-align:left;"> 3.7% </td>
  </tr>
</tbody>
</table>


#### Barplot

![](Codebook_files/figure-html/barplot-Multiple-Choice-Question-8069-Item-7609-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 1050 / 1052

Missing = 2
Min = 0, Max = 1, Mean = 0.01, SD = 0.12
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = 1.15 


#### Screenshot



</div>


</div> <!-- Header section -->

<div class = "header-shading">

#### While AT a Recovery Center, which of the following activities/services did you take part in? Please check all that apply  (Scroll down for all responses) <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7610-anchor"> [Item 7610] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8070-anchor">
  <strong>Question ID</strong>: Question 8070
</div>

**Way the question was delivered:** Multiple Select

**Type of data:** integer

</div> 
<div class = "anchor">




<button 
  onclick="let e = document.getElementById('Question 8070');
           let arrow = document.getElementById('Question 8070_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8070_arrow">▼</span>
</button>

<div id="Question 8070" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Frequency Table

<table class="table" style="color: black; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> Value </th>
   <th style="text-align:left;"> Label </th>
   <th style="text-align:left;"> Counts </th>
   <th style="text-align:left;"> Percentages </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:left;"> Attended a recovery support group meeting (e.g., 12 step or ANY other group meeting) </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 75 </td>
   <td style="text-align:left;"> 19.2% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2 </td>
   <td style="text-align:left;"> Just hung out/ social activities </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 36 </td>
   <td style="text-align:left;"> 9.2% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 3 </td>
   <td style="text-align:left;"> Volunteered/gave back to community </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 32 </td>
   <td style="text-align:left;"> 8.2% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 4 </td>
   <td style="text-align:left;"> Connected to the recovery community </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 66 </td>
   <td style="text-align:left;"> 16.9% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 5 </td>
   <td style="text-align:left;"> Used computer or internet or WiFi </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 29 </td>
   <td style="text-align:left;"> 7.4% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 6 </td>
   <td style="text-align:left;"> Received recovery coaching </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 18 </td>
   <td style="text-align:left;"> 4.6% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 7 </td>
   <td style="text-align:left;"> Tried to help or be there for others </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 69 </td>
   <td style="text-align:left;"> 17.6% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 8 </td>
   <td style="text-align:left;"> Got advice for financial, legal, housing, education, psychological, or medical issues </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 20 </td>
   <td style="text-align:left;"> 5.1% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 9 </td>
   <td style="text-align:left;"> Took part in health/exercise/meditation/self-care class </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 15 </td>
   <td style="text-align:left;"> 3.8% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 10 </td>
   <td style="text-align:left;"> Other (write in) </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 31 </td>
   <td style="text-align:left;"> 7.9% </td>
  </tr>
</tbody>
</table>


#### Barplot

![](Codebook_files/figure-html/barplot-Multiple-Select-Question-8070-Item-7610-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 179 / 179

Missing = 0
Min = 0, Max = 0, Mean = 0, SD = 0
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = NaN 


#### Screenshot



</div>


</div> <!-- Header section -->

<div class = "header-shading">

#### Please specify activity: <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7679-anchor"> [Item 7679] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8179-anchor">
  <strong>Question ID</strong>: Question 8179
</div>

**Way the question was delivered:** Free Response

**Type of data:** character

</div> <div class = "anchor">






<button 
  onclick="let e = document.getElementById('Question 8179');
           let arrow = document.getElementById('Question 8179_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8179_arrow">▼</span>
</button>

<div id="Question 8179" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 31 / 109

Missing = 78
Min = 0, Max = 9, Mean = 1.9, SD = 2.35
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = -1.66 


#### Screenshot



</div>


</div> <!-- Header section -->

<div class = "header-shading">

#### Which recovery support meetings did you attend today? Check all that apply.  (Scroll down for all responses) <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7611-anchor"> [Item 7611] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8071-anchor">
  <strong>Question ID</strong>: Question 8071
</div>

**Way the question was delivered:** Multiple Select

**Type of data:** integer

</div> 
<div class = "anchor">




<button 
  onclick="let e = document.getElementById('Question 8071');
           let arrow = document.getElementById('Question 8071_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8071_arrow">▼</span>
</button>

<div id="Question 8071" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Frequency Table

<table class="table" style="color: black; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:left;"> Value </th>
   <th style="text-align:left;"> Label </th>
   <th style="text-align:left;"> Counts </th>
   <th style="text-align:left;"> Percentages </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:left;color: darkgreen !important;"> “All Recovery” </td>
   <td style="text-align:left;"> N = 2 </td>
   <td style="text-align:left;"> 2.2% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2 </td>
   <td style="text-align:left;"> 2 </td>
   <td style="text-align:left;color: darkgreen !important;"> Dual Recovery Anonymous </td>
   <td style="text-align:left;"> N = 2 </td>
   <td style="text-align:left;"> 2.2% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 3 </td>
   <td style="text-align:left;"> 3 </td>
   <td style="text-align:left;color: darkgreen !important;"> Recovery Life </td>
   <td style="text-align:left;"> N = 2 </td>
   <td style="text-align:left;"> 2.2% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 4 </td>
   <td style="text-align:left;"> 4 </td>
   <td style="text-align:left;color: darkgreen !important;"> SMART Recovery </td>
   <td style="text-align:left;"> N = 5 </td>
   <td style="text-align:left;"> 5.4% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 6 </td>
   <td style="text-align:left;"> 6 </td>
   <td style="text-align:left;color: darkgreen !important;"> AA/NA/HA (12-step oriented meeting) </td>
   <td style="text-align:left;"> N = 62 </td>
   <td style="text-align:left;"> 66.7% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 7 </td>
   <td style="text-align:left;"> 7 </td>
   <td style="text-align:left;color: darkgreen !important;"> MAT/MAR Meeting </td>
   <td style="text-align:left;"> N = 1 </td>
   <td style="text-align:left;"> 1.1% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 8 </td>
   <td style="text-align:left;"> 8 </td>
   <td style="text-align:left;color: darkgreen !important;"> Mindfulness-based recovery </td>
   <td style="text-align:left;"> N = 4 </td>
   <td style="text-align:left;"> 4.3% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 9 </td>
   <td style="text-align:left;"> 9 </td>
   <td style="text-align:left;color: darkgreen !important;"> Grief support </td>
   <td style="text-align:left;"> N = 1 </td>
   <td style="text-align:left;"> 1.1% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 10 </td>
   <td style="text-align:left;"> 10 </td>
   <td style="text-align:left;color: darkgreen !important;"> Faith-based Meeting </td>
   <td style="text-align:left;"> N = 9 </td>
   <td style="text-align:left;"> 9.7% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 11 </td>
   <td style="text-align:left;"> 11 </td>
   <td style="text-align:left;color: darkgreen !important;"> Other </td>
   <td style="text-align:left;"> N = 5 </td>
   <td style="text-align:left;"> 5.4% </td>
  </tr>
</tbody>
</table>


#### Barplot

![](Codebook_files/figure-html/barplot-Multiple-Select-Question-8071-Item-7611-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 75 / 75

Missing = 0
Min = 0, Max = 0, Mean = 0, SD = 0
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = NaN 


#### Screenshot



</div>


</div> <!-- Header section -->

<div class = "header-shading">

#### When thinking about your time at the Recovery Center today... <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7621-anchor"> [Item 7621] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8072-anchor">
  <strong>Question ID</strong>: Question 8072
</div>

**Way the question was delivered:** Informational Fullscreen

**Type of data:** NA

</div> <div class = "anchor">







</div> <!-- Header section -->

<div class = "header-shading">

#### How helpful was being at the Recovery Center to your recovery? <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7612-anchor"> [Item 7612] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8073-anchor">
  <strong>Question ID</strong>: Question 8073
</div>

**Way the question was delivered:** Slider

**Type of data:** numeric

</div> <div class = "anchor">






**Descriptives**
Min = 0, Max = 100, Mean = 82.87, SD = 19.89 



<button 
  onclick="let e = document.getElementById('Question 8073');
           let arrow = document.getElementById('Question 8073_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8073_arrow">▼</span>
</button>

<div id="Question 8073" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram

![](Codebook_files/figure-html/histogram-Slider-Question-8073-Item-7612-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 178 / 179

Missing = 1
Min = 0, Max = 1, Mean = 0.01, SD = 0.12
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = 1.65 



#### Screenshot


</div>

</div> <!-- Header section -->

<div class = "header-shading">

#### How helpful was being at the Recovery Center to your overall well-being? <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7614-anchor"> [Item 7614] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8074-anchor">
  <strong>Question ID</strong>: Question 8074
</div>

**Way the question was delivered:** Slider

**Type of data:** numeric

</div> <div class = "anchor">






**Descriptives**
Min = 0, Max = 100, Mean = 83.44, SD = 19.83 



<button 
  onclick="let e = document.getElementById('Question 8074');
           let arrow = document.getElementById('Question 8074_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8074_arrow">▼</span>
</button>

<div id="Question 8074" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram

![](Codebook_files/figure-html/histogram-Slider-Question-8074-Item-7614-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 179 / 179

Missing = 0
Min = 0, Max = 0, Mean = 0, SD = 0
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = NaN 



#### Screenshot


</div>

</div> <!-- Header section -->

<div class = "header-shading">

#### Do you reside in a recovery house? <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7616-anchor"> [Item 7616] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8075-anchor">
  <strong>Question ID</strong>: Question 8075
</div>

**Way the question was delivered:** Multiple Choice

**Type of data:** integer

</div> 
<div class = "anchor">




<button 
  onclick="let e = document.getElementById('Question 8075');
           let arrow = document.getElementById('Question 8075_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8075_arrow">▼</span>
</button>

<div id="Question 8075" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Frequency Table

<table class="table" style="color: black; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> Value </th>
   <th style="text-align:left;"> Label </th>
   <th style="text-align:left;"> Counts </th>
   <th style="text-align:left;"> Percentages </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:left;"> Yes </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 38 </td>
   <td style="text-align:left;"> 3.6% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2 </td>
   <td style="text-align:left;"> No </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 1010 </td>
   <td style="text-align:left;"> 96.4% </td>
  </tr>
</tbody>
</table>


#### Barplot

![](Codebook_files/figure-html/barplot-Multiple-Choice-Question-8075-Item-7616-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 1048 / 1051

Missing = 3
Min = 0, Max = 1, Mean = 0.02, SD = 0.15
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = 1.15 


#### Screenshot



</div>


</div> <!-- Header section -->

<div class = "header-shading">

#### How much time did you spend at a recovery house today (NOT counting sleeping time)?(Scroll down for all responses) <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7617-anchor"> [Item 7617] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8076-anchor">
  <strong>Question ID</strong>: Question 8076
</div>

**Way the question was delivered:** Multiple Choice

**Type of data:** integer

</div> 
<div class = "anchor">




<button 
  onclick="let e = document.getElementById('Question 8076');
           let arrow = document.getElementById('Question 8076_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8076_arrow">▼</span>
</button>

<div id="Question 8076" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Frequency Table

<table class="table" style="color: black; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> Value </th>
   <th style="text-align:left;"> Label </th>
   <th style="text-align:left;"> Counts </th>
   <th style="text-align:left;"> Percentages </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:left;"> 0 minutes – I did not sleep there last night </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 1 </td>
   <td style="text-align:left;"> 2.6% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2 </td>
   <td style="text-align:left;"> 1 – 30 minutes </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 3 </td>
   <td style="text-align:left;"> 7.9% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 3 </td>
   <td style="text-align:left;"> 30 – 60 minutes </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 3 </td>
   <td style="text-align:left;"> 7.9% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 4 </td>
   <td style="text-align:left;"> 1 – 2 hours </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 7 </td>
   <td style="text-align:left;"> 18.4% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 5 </td>
   <td style="text-align:left;"> 2 – 4 hours </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 2 </td>
   <td style="text-align:left;"> 5.3% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 6 </td>
   <td style="text-align:left;"> 4 – 6  hours </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 7 </td>
   <td style="text-align:left;"> 18.4% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 7 </td>
   <td style="text-align:left;"> More than 6 hours </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 15 </td>
   <td style="text-align:left;"> 39.5% </td>
  </tr>
</tbody>
</table>


#### Barplot

![](Codebook_files/figure-html/barplot-Multiple-Choice-Question-8076-Item-7617-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 38 / 38

Missing = 0
Min = 0, Max = 0, Mean = 0, SD = 0
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = NaN 


#### Screenshot



</div>


</div> <!-- Header section -->

<div class = "header-shading">

#### While AT YOUR RECOVERY HOUSE, which of the following activities/services did you take part in? Please check all that apply  (Scroll down for all responses) <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7618-anchor"> [Item 7618] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8077-anchor">
  <strong>Question ID</strong>: Question 8077
</div>

**Way the question was delivered:** Multiple Select

**Type of data:** integer

</div> 
<div class = "anchor">




<button 
  onclick="let e = document.getElementById('Question 8077');
           let arrow = document.getElementById('Question 8077_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8077_arrow">▼</span>
</button>

<div id="Question 8077" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Frequency Table

<table class="table" style="color: black; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:left;"> Value </th>
   <th style="text-align:left;"> Label </th>
   <th style="text-align:left;"> Counts </th>
   <th style="text-align:left;"> Percentages </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:left;color: darkgreen !important;"> I ate meals </td>
   <td style="text-align:left;"> N = 31 </td>
   <td style="text-align:left;"> 18.8% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2 </td>
   <td style="text-align:left;"> 2 </td>
   <td style="text-align:left;color: darkgreen !important;"> I cooked meals </td>
   <td style="text-align:left;"> N = 24 </td>
   <td style="text-align:left;"> 14.5% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 3 </td>
   <td style="text-align:left;"> 3 </td>
   <td style="text-align:left;color: darkgreen !important;"> I did house chores </td>
   <td style="text-align:left;"> N = 24 </td>
   <td style="text-align:left;"> 14.5% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 4 </td>
   <td style="text-align:left;"> 4 </td>
   <td style="text-align:left;color: darkgreen !important;"> I spent time by myself </td>
   <td style="text-align:left;"> N = 21 </td>
   <td style="text-align:left;"> 12.7% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 5 </td>
   <td style="text-align:left;"> 5 </td>
   <td style="text-align:left;color: darkgreen !important;"> Attended a recovery support group meeting (e.g., 12 step or ANY other group meeting) </td>
   <td style="text-align:left;"> N = 7 </td>
   <td style="text-align:left;"> 4.2% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 6 </td>
   <td style="text-align:left;"> 6 </td>
   <td style="text-align:left;color: darkgreen !important;"> Just hung out/ social activities </td>
   <td style="text-align:left;"> N = 15 </td>
   <td style="text-align:left;"> 9.1% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 7 </td>
   <td style="text-align:left;"> 7 </td>
   <td style="text-align:left;color: darkgreen !important;"> Volunteered/gave back to community </td>
   <td style="text-align:left;"> N = 4 </td>
   <td style="text-align:left;"> 2.4% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 8 </td>
   <td style="text-align:left;"> 8 </td>
   <td style="text-align:left;color: darkgreen !important;"> Connected to the recovery community </td>
   <td style="text-align:left;"> N = 3 </td>
   <td style="text-align:left;"> 1.8% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 9 </td>
   <td style="text-align:left;"> 9 </td>
   <td style="text-align:left;color: darkgreen !important;"> Used computer or internet or WiF </td>
   <td style="text-align:left;"> N = 23 </td>
   <td style="text-align:left;"> 13.9% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 11 </td>
   <td style="text-align:left;"> 11 </td>
   <td style="text-align:left;color: darkgreen !important;"> Tried to help or be there for others </td>
   <td style="text-align:left;"> N = 7 </td>
   <td style="text-align:left;"> 4.2% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 12 </td>
   <td style="text-align:left;"> 12 </td>
   <td style="text-align:left;color: darkgreen !important;"> Got advice for financial, legal, housing, education, psychological, or medical issues </td>
   <td style="text-align:left;"> N = 2 </td>
   <td style="text-align:left;"> 1.2% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 13 </td>
   <td style="text-align:left;"> 13 </td>
   <td style="text-align:left;color: darkgreen !important;"> Took part in health/exercise/meditation/self-care class </td>
   <td style="text-align:left;"> N = 1 </td>
   <td style="text-align:left;"> 0.6% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 14 </td>
   <td style="text-align:left;"> 14 </td>
   <td style="text-align:left;color: darkgreen !important;"> Other (write in) </td>
   <td style="text-align:left;"> N = 3 </td>
   <td style="text-align:left;"> 1.8% </td>
  </tr>
</tbody>
</table>


#### Barplot

![](Codebook_files/figure-html/barplot-Multiple-Select-Question-8077-Item-7618-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 36 / 36

Missing = 0
Min = 0, Max = 0, Mean = 0, SD = 0
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = NaN 


#### Screenshot



</div>


</div> <!-- Header section -->

<div class = "header-shading">

#### Please specify activity: <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7619-anchor"> [Item 7619] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8078-anchor">
  <strong>Question ID</strong>: Question 8078
</div>

**Way the question was delivered:** Free Response

**Type of data:** character

</div> <div class = "anchor">






<button 
  onclick="let e = document.getElementById('Question 8078');
           let arrow = document.getElementById('Question 8078_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8078_arrow">▼</span>
</button>

<div id="Question 8078" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 1 / 34

Missing = 33
Min = 1, Max = 10, Mean = 4.71, SD = 4.39
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = -0.02 


#### Screenshot



</div>


</div> <!-- Header section -->

<div class = "header-shading">

#### Please check off any recovery support meetings you attended today? Select all that apply  (Scroll down for all responses) <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7620-anchor"> [Item 7620] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8079-anchor">
  <strong>Question ID</strong>: Question 8079
</div>

**Way the question was delivered:** Multiple Select

**Type of data:** integer

</div> 
<div class = "anchor">




<button 
  onclick="let e = document.getElementById('Question 8079');
           let arrow = document.getElementById('Question 8079_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8079_arrow">▼</span>
</button>

<div id="Question 8079" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Frequency Table

<table class="table" style="color: black; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:left;"> Value </th>
   <th style="text-align:left;"> Label </th>
   <th style="text-align:left;"> Counts </th>
   <th style="text-align:left;"> Percentages </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:left;color: darkgreen !important;"> “All Recovery” </td>
   <td style="text-align:left;"> N = 2 </td>
   <td style="text-align:left;"> 15.4% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2 </td>
   <td style="text-align:left;"> 2 </td>
   <td style="text-align:left;color: darkgreen !important;"> Dual Recovery Anonymous </td>
   <td style="text-align:left;"> N = 1 </td>
   <td style="text-align:left;"> 7.7% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 3 </td>
   <td style="text-align:left;"> 3 </td>
   <td style="text-align:left;color: darkgreen !important;"> Recovery Life </td>
   <td style="text-align:left;"> N = 2 </td>
   <td style="text-align:left;"> 15.4% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 5 </td>
   <td style="text-align:left;"> 5 </td>
   <td style="text-align:left;color: darkgreen !important;"> Gambler’s Anonymous </td>
   <td style="text-align:left;"> N = 1 </td>
   <td style="text-align:left;"> 7.7% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 6 </td>
   <td style="text-align:left;"> 6 </td>
   <td style="text-align:left;color: darkgreen !important;"> AA/NA/HA (12-step oriented meeting) </td>
   <td style="text-align:left;"> N = 1 </td>
   <td style="text-align:left;"> 7.7% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 8 </td>
   <td style="text-align:left;"> 8 </td>
   <td style="text-align:left;color: darkgreen !important;"> Mindfulness-based recovery </td>
   <td style="text-align:left;"> N = 1 </td>
   <td style="text-align:left;"> 7.7% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 9 </td>
   <td style="text-align:left;"> 9 </td>
   <td style="text-align:left;color: darkgreen !important;"> Grief support </td>
   <td style="text-align:left;"> N = 1 </td>
   <td style="text-align:left;"> 7.7% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 10 </td>
   <td style="text-align:left;"> 10 </td>
   <td style="text-align:left;color: darkgreen !important;"> Faith-based Meeting </td>
   <td style="text-align:left;"> N = 3 </td>
   <td style="text-align:left;"> 23.1% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 11 </td>
   <td style="text-align:left;"> 11 </td>
   <td style="text-align:left;color: darkgreen !important;"> Other </td>
   <td style="text-align:left;"> N = 1 </td>
   <td style="text-align:left;"> 7.7% </td>
  </tr>
</tbody>
</table>


#### Barplot

![](Codebook_files/figure-html/barplot-Multiple-Select-Question-8079-Item-7620-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 7 / 36

Missing = 29
Min = 0, Max = 10, Mean = 3.22, SD = 4.18
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = -4.56 


#### Screenshot



</div>


</div> <!-- Header section -->

<div class = "header-shading">

#### When thinking about your time at the recovery house today... <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7622-anchor"> [Item 7622] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8080-anchor">
  <strong>Question ID</strong>: Question 8080
</div>

**Way the question was delivered:** Informational Fullscreen

**Type of data:** NA

</div> <div class = "anchor">







</div> <!-- Header section -->

<div class = "header-shading">

#### How helpful was being at the recovery house to your recovery? <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7623-anchor"> [Item 7623] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8081-anchor">
  <strong>Question ID</strong>: Question 8081
</div>

**Way the question was delivered:** Slider

**Type of data:** numeric

</div> <div class = "anchor">






**Descriptives**
Min = 15, Max = 100, Mean = 75.39, SD = 25.08 



<button 
  onclick="let e = document.getElementById('Question 8081');
           let arrow = document.getElementById('Question 8081_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8081_arrow">▼</span>
</button>

<div id="Question 8081" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram

![](Codebook_files/figure-html/histogram-Slider-Question-8081-Item-7623-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 36 / 36

Missing = 0
Min = 0, Max = 0, Mean = 0, SD = 0
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = NaN 



#### Screenshot


</div>

</div> <!-- Header section -->

<div class = "header-shading">

#### How helpful was being at the recovery house to your overall well-being? <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7624-anchor"> [Item 7624] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8082-anchor">
  <strong>Question ID</strong>: Question 8082
</div>

**Way the question was delivered:** Slider

**Type of data:** numeric

</div> <div class = "anchor">






**Descriptives**
Min = 19, Max = 100, Mean = 76.72, SD = 22.55 



<button 
  onclick="let e = document.getElementById('Question 8082');
           let arrow = document.getElementById('Question 8082_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8082_arrow">▼</span>
</button>

<div id="Question 8082" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram

![](Codebook_files/figure-html/histogram-Slider-Question-8082-Item-7624-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 36 / 36

Missing = 0
Min = 0, Max = 0, Mean = 0, SD = 0
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = NaN 



#### Screenshot


</div>

</div> <!-- Header section -->

<div class = "header-shading">

#### End Block <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7638-anchor"> [Item 7638] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8083-anchor">
  <strong>Question ID</strong>: Question 8083
</div>

**Way the question was delivered:** End Block

**Type of data:** NA

</div>  <!-- Header section -->

<div class = "header-shading">

#### While NOT AT A RCC OR RECOVERY HOUSE, which of the following activities/services did you take part in?  Please check all that apply  (Scroll down for all responses) <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7625-anchor"> [Item 7625] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8084-anchor">
  <strong>Question ID</strong>: Question 8084
</div>

**Way the question was delivered:** Multiple Select

**Type of data:** integer

</div> 
<div class = "anchor">




<button 
  onclick="let e = document.getElementById('Question 8084');
           let arrow = document.getElementById('Question 8084_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8084_arrow">▼</span>
</button>

<div id="Question 8084" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Frequency Table

<table class="table" style="color: black; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> Value </th>
   <th style="text-align:left;"> Label </th>
   <th style="text-align:left;"> Counts </th>
   <th style="text-align:left;"> Percentages </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:left;"> Attended a recovery support group meeting (e.g., 12 step or ANY other group meeting). </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 212 </td>
   <td style="text-align:left;"> 10.9% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2 </td>
   <td style="text-align:left;"> Just hung out with others/ social activities </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 299 </td>
   <td style="text-align:left;"> 15.3% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 3 </td>
   <td style="text-align:left;"> Volunteered/gave back to community </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 109 </td>
   <td style="text-align:left;"> 5.6% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 4 </td>
   <td style="text-align:left;"> Connected to the recovery community </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 257 </td>
   <td style="text-align:left;"> 13.2% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 5 </td>
   <td style="text-align:left;"> Received recovery coaching </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 29 </td>
   <td style="text-align:left;"> 1.5% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 6 </td>
   <td style="text-align:left;"> Tried to help or be there for others </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 437 </td>
   <td style="text-align:left;"> 22.4% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 7 </td>
   <td style="text-align:left;"> Got advice for financial, legal, housing, education, psychological, or medical issues </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 100 </td>
   <td style="text-align:left;"> 5.1% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 8 </td>
   <td style="text-align:left;"> Took part in health/exercise/meditation/self-care class </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 211 </td>
   <td style="text-align:left;"> 10.8% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 9 </td>
   <td style="text-align:left;"> Other (write in) </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 78 </td>
   <td style="text-align:left;"> 4% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 10 </td>
   <td style="text-align:left;"> None of the above </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 219 </td>
   <td style="text-align:left;"> 11.2% </td>
  </tr>
</tbody>
</table>


#### Barplot

![](Codebook_files/figure-html/barplot-Multiple-Select-Question-8084-Item-7625-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 1046 / 1048

Missing = 2
Min = 0, Max = 1, Mean = 0.01, SD = 0.12
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = 1.15 


#### Screenshot



</div>


</div> <!-- Header section -->

<div class = "header-shading">

#### Please specify activity: <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7626-anchor"> [Item 7626] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8085-anchor">
  <strong>Question ID</strong>: Question 8085
</div>

**Way the question was delivered:** Free Response

**Type of data:** character

</div> <div class = "anchor">






<button 
  onclick="let e = document.getElementById('Question 8085');
           let arrow = document.getElementById('Question 8085_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8085_arrow">▼</span>
</button>

<div id="Question 8085" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 76 / 587

Missing = 511
Min = 0, Max = 12, Mean = 5.74, SD = 4.13
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = -0.49 


#### Screenshot



</div>


</div> <!-- Header section -->

<div class = "header-shading">

#### Please check off any recovery support meetings you attended today while NOT AT A RCC OR RECOVERY HOUSE? Select all that apply.  (Scroll down for all responses) <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7628-anchor"> [Item 7628] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8180-anchor">
  <strong>Question ID</strong>: Question 8180
</div>

**Way the question was delivered:** Multiple Select

**Type of data:** integer

</div> 
<div class = "anchor">




<button 
  onclick="let e = document.getElementById('Question 8180');
           let arrow = document.getElementById('Question 8180_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8180_arrow">▼</span>
</button>

<div id="Question 8180" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Frequency Table

<table class="table" style="color: black; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:left;"> Value </th>
   <th style="text-align:left;"> Label </th>
   <th style="text-align:left;"> Counts </th>
   <th style="text-align:left;"> Percentages </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:left;color: darkgreen !important;"> “All Recovery” </td>
   <td style="text-align:left;"> N = 4 </td>
   <td style="text-align:left;"> 1.6% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2 </td>
   <td style="text-align:left;"> 2 </td>
   <td style="text-align:left;color: darkgreen !important;"> Dual Recovery Anonymous </td>
   <td style="text-align:left;"> N = 6 </td>
   <td style="text-align:left;"> 2.4% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 3 </td>
   <td style="text-align:left;"> 3 </td>
   <td style="text-align:left;color: darkgreen !important;"> Recovery Life </td>
   <td style="text-align:left;"> N = 1 </td>
   <td style="text-align:left;"> 0.4% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 4 </td>
   <td style="text-align:left;"> 4 </td>
   <td style="text-align:left;color: darkgreen !important;"> SMART Recovery </td>
   <td style="text-align:left;"> N = 13 </td>
   <td style="text-align:left;"> 5.1% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 6 </td>
   <td style="text-align:left;"> 6 </td>
   <td style="text-align:left;color: darkgreen !important;"> AA/NA/HA (12-step oriented meeting) </td>
   <td style="text-align:left;"> N = 182 </td>
   <td style="text-align:left;"> 71.4% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 7 </td>
   <td style="text-align:left;"> 7 </td>
   <td style="text-align:left;color: darkgreen !important;"> MAT/MAR Meeting </td>
   <td style="text-align:left;"> N = 2 </td>
   <td style="text-align:left;"> 0.8% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 8 </td>
   <td style="text-align:left;"> 8 </td>
   <td style="text-align:left;color: darkgreen !important;"> Mindfulness-based recovery </td>
   <td style="text-align:left;"> N = 7 </td>
   <td style="text-align:left;"> 2.7% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 9 </td>
   <td style="text-align:left;"> 9 </td>
   <td style="text-align:left;color: darkgreen !important;"> Grief support </td>
   <td style="text-align:left;"> N = 6 </td>
   <td style="text-align:left;"> 2.4% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 10 </td>
   <td style="text-align:left;"> 10 </td>
   <td style="text-align:left;color: darkgreen !important;"> Faith-based Meeting </td>
   <td style="text-align:left;"> N = 20 </td>
   <td style="text-align:left;"> 7.8% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 11 </td>
   <td style="text-align:left;"> 11 </td>
   <td style="text-align:left;color: darkgreen !important;"> Other </td>
   <td style="text-align:left;"> N = 14 </td>
   <td style="text-align:left;"> 5.5% </td>
  </tr>
</tbody>
</table>


#### Barplot

![](Codebook_files/figure-html/barplot-Multiple-Select-Question-8180-Item-7628-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 209 / 209

Missing = 0
Min = 0, Max = 0, Mean = 0, SD = 0
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = NaN 


#### Screenshot



</div>


</div> <!-- Header section -->

<div class = "header-shading">

#### Where did you attend the meeting or meetings? Select all that apply  (Scroll down for all responses) <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7629-anchor"> [Item 7629] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8087-anchor">
  <strong>Question ID</strong>: Question 8087
</div>

**Way the question was delivered:** Multiple Select

**Type of data:** integer

</div> 
<div class = "anchor">




<button 
  onclick="let e = document.getElementById('Question 8087');
           let arrow = document.getElementById('Question 8087_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8087_arrow">▼</span>
</button>

<div id="Question 8087" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Frequency Table

<table class="table" style="color: black; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> Value </th>
   <th style="text-align:left;"> Label </th>
   <th style="text-align:left;"> Counts </th>
   <th style="text-align:left;"> Percentages </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:left;"> Church/religious institution </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 106 </td>
   <td style="text-align:left;"> 41.4% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2 </td>
   <td style="text-align:left;"> School </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 5 </td>
   <td style="text-align:left;"> 2% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 3 </td>
   <td style="text-align:left;"> Other government building </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 6 </td>
   <td style="text-align:left;"> 2.3% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 4 </td>
   <td style="text-align:left;"> Clubhouse </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 28 </td>
   <td style="text-align:left;"> 10.9% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 5 </td>
   <td style="text-align:left;"> Community center </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 21 </td>
   <td style="text-align:left;"> 8.2% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 6 </td>
   <td style="text-align:left;"> Online </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 60 </td>
   <td style="text-align:left;"> 23.4% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 7 </td>
   <td style="text-align:left;"> Other </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 30 </td>
   <td style="text-align:left;"> 11.7% </td>
  </tr>
</tbody>
</table>


#### Barplot

![](Codebook_files/figure-html/barplot-Multiple-Select-Question-8087-Item-7629-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 212 / 212

Missing = 0
Min = 0, Max = 0, Mean = 0, SD = 0
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = NaN 


#### Screenshot



</div>


</div> <!-- Header section -->

<div class = "header-shading">

#### When thinking about your full day... <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7631-anchor"> [Item 7631] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8088-anchor">
  <strong>Question ID</strong>: Question 8088
</div>

**Way the question was delivered:** Informational Fullscreen

**Type of data:** NA

</div> <div class = "anchor">







</div> <!-- Header section -->

<div class = "header-shading">

#### How helpful were your days experiences to your recovery? <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7632-anchor"> [Item 7632] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8089-anchor">
  <strong>Question ID</strong>: Question 8089
</div>

**Way the question was delivered:** Slider

**Type of data:** numeric

</div> <div class = "anchor">






**Descriptives**
Min = 0, Max = 100, Mean = 75.15, SD = 23.74 



<button 
  onclick="let e = document.getElementById('Question 8089');
           let arrow = document.getElementById('Question 8089_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8089_arrow">▼</span>
</button>

<div id="Question 8089" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram

![](Codebook_files/figure-html/histogram-Slider-Question-8089-Item-7632-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 1045 / 1048

Missing = 3
Min = 0, Max = 1, Mean = 0.02, SD = 0.15
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = 1.15 



#### Screenshot


</div>

</div> <!-- Header section -->

<div class = "header-shading">

#### How helpful were your days experiences to your overall well-being? <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7633-anchor"> [Item 7633] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8090-anchor">
  <strong>Question ID</strong>: Question 8090
</div>

**Way the question was delivered:** Slider

**Type of data:** numeric

</div> <div class = "anchor">






**Descriptives**
Min = 0, Max = 100, Mean = 77.81, SD = 22.31 



<button 
  onclick="let e = document.getElementById('Question 8090');
           let arrow = document.getElementById('Question 8090_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8090_arrow">▼</span>
</button>

<div id="Question 8090" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram

![](Codebook_files/figure-html/histogram-Slider-Question-8090-Item-7633-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 1045 / 1047

Missing = 2
Min = 0, Max = 1, Mean = 0.01, SD = 0.12
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = 1.15 



#### Screenshot


</div>

</div> <!-- Header section -->

<div class = "header-shading">

#### If you did not go to a recovery support meeting today, what was the reason? Check off all that apply.  (Scroll down for all responses) <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7639-anchor"> [Item 7639] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8181-anchor">
  <strong>Question ID</strong>: Question 8181
</div>

**Way the question was delivered:** Multiple Select

**Type of data:** integer

</div> 
<div class = "anchor">




<button 
  onclick="let e = document.getElementById('Question 8181');
           let arrow = document.getElementById('Question 8181_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8181_arrow">▼</span>
</button>

<div id="Question 8181" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Frequency Table

<table class="table" style="color: black; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> Value </th>
   <th style="text-align:left;"> Label </th>
   <th style="text-align:left;"> Counts </th>
   <th style="text-align:left;"> Percentages </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:left;"> Actually, I did go to one </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 233 </td>
   <td style="text-align:left;"> 19.3% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2 </td>
   <td style="text-align:left;"> Just too busy </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 133 </td>
   <td style="text-align:left;"> 11% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 3 </td>
   <td style="text-align:left;"> I didn’t feel like it </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 91 </td>
   <td style="text-align:left;"> 7.5% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 4 </td>
   <td style="text-align:left;"> I attend on a different day of the week </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 189 </td>
   <td style="text-align:left;"> 15.6% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 5 </td>
   <td style="text-align:left;"> Transportation problems </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 19 </td>
   <td style="text-align:left;"> 1.6% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 6 </td>
   <td style="text-align:left;"> I don’t go to meetings </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 258 </td>
   <td style="text-align:left;"> 21.3% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 7 </td>
   <td style="text-align:left;"> Work conflicts </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 98 </td>
   <td style="text-align:left;"> 8.1% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 8 </td>
   <td style="text-align:left;"> Caregiving responsibilities </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 65 </td>
   <td style="text-align:left;"> 5.4% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 9 </td>
   <td style="text-align:left;"> Other </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 123 </td>
   <td style="text-align:left;"> 10.2% </td>
  </tr>
</tbody>
</table>


#### Barplot

![](Codebook_files/figure-html/barplot-Multiple-Select-Question-8181-Item-7639-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 1037 / 1043

Missing = 6
Min = 0, Max = 2, Mean = 0.05, SD = 0.24
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = 1.11 


#### Screenshot



</div>


</div> <!-- Header section -->

<div class = "header-shading">

#### How difficult was it to get where you needed to go today? <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7640-anchor"> [Item 7640] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8092-anchor">
  <strong>Question ID</strong>: Question 8092
</div>

**Way the question was delivered:** Multiple Choice

**Type of data:** integer

</div> 
<div class = "anchor">




<button 
  onclick="let e = document.getElementById('Question 8092');
           let arrow = document.getElementById('Question 8092_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8092_arrow">▼</span>
</button>

<div id="Question 8092" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Frequency Table

<table class="table" style="color: black; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> Value </th>
   <th style="text-align:left;"> Label </th>
   <th style="text-align:left;"> Counts </th>
   <th style="text-align:left;"> Percentages </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:left;"> Extremely Difficult </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 7 </td>
   <td style="text-align:left;"> 0.7% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2 </td>
   <td style="text-align:left;"> Very difficult </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 15 </td>
   <td style="text-align:left;"> 1.4% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 3 </td>
   <td style="text-align:left;"> Moderately Difficult </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 32 </td>
   <td style="text-align:left;"> 3.1% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 4 </td>
   <td style="text-align:left;"> Slightly Difficult </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 87 </td>
   <td style="text-align:left;"> 8.3% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 5 </td>
   <td style="text-align:left;"> Not at all Difficult </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 902 </td>
   <td style="text-align:left;"> 86.5% </td>
  </tr>
</tbody>
</table>


#### Barplot

![](Codebook_files/figure-html/barplot-Multiple-Choice-Question-8092-Item-7640-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 1043 / 1046

Missing = 3
Min = 0, Max = 1, Mean = 0.02, SD = 0.15
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = 1.15 


#### Screenshot



</div>


</div> <!-- Header section -->

<div class = "header-shading">

#### Did you work for pay today? <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7641-anchor"> [Item 7641] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8093-anchor">
  <strong>Question ID</strong>: Question 8093
</div>

**Way the question was delivered:** Multiple Choice

**Type of data:** integer

</div> 
<div class = "anchor">




<button 
  onclick="let e = document.getElementById('Question 8093');
           let arrow = document.getElementById('Question 8093_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8093_arrow">▼</span>
</button>

<div id="Question 8093" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Frequency Table

<table class="table" style="color: black; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> Value </th>
   <th style="text-align:left;"> Label </th>
   <th style="text-align:left;"> Counts </th>
   <th style="text-align:left;"> Percentages </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:left;"> Yes </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 518 </td>
   <td style="text-align:left;"> 49.6% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2 </td>
   <td style="text-align:left;"> No </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 526 </td>
   <td style="text-align:left;"> 50.4% </td>
  </tr>
</tbody>
</table>


#### Barplot

![](Codebook_files/figure-html/barplot-Multiple-Choice-Question-8093-Item-7641-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 1044 / 1046

Missing = 2
Min = 0, Max = 1, Mean = 0.02, SD = 0.12
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = 1.15 


#### Screenshot



</div>


</div> <!-- Header section -->

<div class = "header-shading">

#### I ENJOYED work <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7642-anchor"> [Item 7642] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8094-anchor">
  <strong>Question ID</strong>: Question 8094
</div>

**Way the question was delivered:** Slider

**Type of data:** numeric

</div> <div class = "anchor">






**Descriptives**
Min = 0, Max = 100, Mean = 74.2, SD = 25.31 



<button 
  onclick="let e = document.getElementById('Question 8094');
           let arrow = document.getElementById('Question 8094_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8094_arrow">▼</span>
</button>

<div id="Question 8094" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram

![](Codebook_files/figure-html/histogram-Slider-Question-8094-Item-7642-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 515 / 518

Missing = 3
Min = 0, Max = 1, Mean = 0.03, SD = 0.17
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = 1.25 



#### Screenshot


</div>

</div> <!-- Header section -->

<div class = "header-shading">

#### I felt COMPETENT at work <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7643-anchor"> [Item 7643] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8095-anchor">
  <strong>Question ID</strong>: Question 8095
</div>

**Way the question was delivered:** Slider

**Type of data:** numeric

</div> <div class = "anchor">






**Descriptives**
Min = 0, Max = 100, Mean = 82.02, SD = 20.36 



<button 
  onclick="let e = document.getElementById('Question 8095');
           let arrow = document.getElementById('Question 8095_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8095_arrow">▼</span>
</button>

<div id="Question 8095" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram

![](Codebook_files/figure-html/histogram-Slider-Question-8095-Item-7643-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 516 / 518

Missing = 2
Min = 0, Max = 1, Mean = 0.02, SD = 0.14
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = 1.25 



#### Screenshot


</div>

</div> <!-- Header section -->

<div class = "header-shading">

#### I felt a sense of ACCOMPLISHMENT at work <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7644-anchor"> [Item 7644] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8096-anchor">
  <strong>Question ID</strong>: Question 8096
</div>

**Way the question was delivered:** Slider

**Type of data:** numeric

</div> <div class = "anchor">






**Descriptives**
Min = 0, Max = 100, Mean = 78.79, SD = 23.43 



<button 
  onclick="let e = document.getElementById('Question 8096');
           let arrow = document.getElementById('Question 8096_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8096_arrow">▼</span>
</button>

<div id="Question 8096" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram

![](Codebook_files/figure-html/histogram-Slider-Question-8096-Item-7644-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 517 / 518

Missing = 1
Min = 0, Max = 1, Mean = 0.01, SD = 0.1
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = 1.24 



#### Screenshot


</div>

</div> <!-- Header section -->

<div class = "header-shading">

#### I felt CONNECTED to my work or with other people at work <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7645-anchor"> [Item 7645] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8097-anchor">
  <strong>Question ID</strong>: Question 8097
</div>

**Way the question was delivered:** Slider

**Type of data:** numeric

</div> <div class = "anchor">






**Descriptives**
Min = 0, Max = 100, Mean = 75.89, SD = 26.26 



<button 
  onclick="let e = document.getElementById('Question 8097');
           let arrow = document.getElementById('Question 8097_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8097_arrow">▼</span>
</button>

<div id="Question 8097" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram

![](Codebook_files/figure-html/histogram-Slider-Question-8097-Item-7645-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 517 / 518

Missing = 1
Min = 0, Max = 1, Mean = 0.01, SD = 0.1
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = 1.24 



#### Screenshot


</div>

</div> <!-- Header section -->

<div class = "header-shading">

#### Why did you not go to work? <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7646-anchor"> [Item 7646] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8098-anchor">
  <strong>Question ID</strong>: Question 8098
</div>

**Way the question was delivered:** Multiple Choice

**Type of data:** integer

</div> 
<div class = "anchor">




<button 
  onclick="let e = document.getElementById('Question 8098');
           let arrow = document.getElementById('Question 8098_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8098_arrow">▼</span>
</button>

<div id="Question 8098" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Frequency Table

<table class="table" style="color: black; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:left;"> Value </th>
   <th style="text-align:left;"> Label </th>
   <th style="text-align:left;"> Counts </th>
   <th style="text-align:left;"> Percentages </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:left;color: darkgreen !important;"> I don’t have a paying job right now </td>
   <td style="text-align:left;"> N = 196 </td>
   <td style="text-align:left;"> 37.3% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2 </td>
   <td style="text-align:left;"> 2 </td>
   <td style="text-align:left;color: darkgreen !important;"> Weekend </td>
   <td style="text-align:left;"> N = 137 </td>
   <td style="text-align:left;"> 26% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 3 </td>
   <td style="text-align:left;"> 3 </td>
   <td style="text-align:left;color: darkgreen !important;"> Not scheduled </td>
   <td style="text-align:left;"> N = 149 </td>
   <td style="text-align:left;"> 28.3% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 4 </td>
   <td style="text-align:left;"> 4 </td>
   <td style="text-align:left;color: darkgreen !important;"> Felt sick </td>
   <td style="text-align:left;"> N = 16 </td>
   <td style="text-align:left;"> 3% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 6 </td>
   <td style="text-align:left;"> 6 </td>
   <td style="text-align:left;color: darkgreen !important;"> Skipped for other reason </td>
   <td style="text-align:left;"> N = 28 </td>
   <td style="text-align:left;"> 5.3% </td>
  </tr>
</tbody>
</table>


#### Barplot

![](Codebook_files/figure-html/barplot-Multiple-Choice-Question-8098-Item-7646-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 526 / 526

Missing = 0
Min = 0, Max = 0, Mean = 0, SD = 0
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = NaN 


#### Screenshot



</div>


</div> <!-- Header section -->

<div class = "header-shading">

#### The following questions ask about how you have felt today  Click below to continue <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7649-anchor"> [Item 7649] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8099-anchor">
  <strong>Question ID</strong>: Question 8099
</div>

**Way the question was delivered:** Informational Fullscreen

**Type of data:** NA

</div> <div class = "anchor">







</div> <!-- Header section -->

<div class = "header-shading">

#### Today... <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7652-anchor"> [Item 7652] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8100-anchor">
  <strong>Question ID</strong>: Question 8100
</div>

**Way the question was delivered:** Informational Fullscreen

**Type of data:** NA

</div> <div class = "anchor">







</div> <!-- Header section -->

<div class = "header-shading">

#### How FREQUENT have your alcohol or drug cravings been? <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7650-anchor"> [Item 7650] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8101-anchor">
  <strong>Question ID</strong>: Question 8101
</div>

**Way the question was delivered:** Slider

**Type of data:** numeric

</div> <div class = "anchor">






**Descriptives**
Min = 0, Max = 100, Mean = 9.73, SD = 18.1 



<button 
  onclick="let e = document.getElementById('Question 8101');
           let arrow = document.getElementById('Question 8101_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8101_arrow">▼</span>
</button>

<div id="Question 8101" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram

![](Codebook_files/figure-html/histogram-Slider-Question-8101-Item-7650-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 1046 / 1046

Missing = 0
Min = 0, Max = 0, Mean = 0, SD = 0
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = NaN 



#### Screenshot


</div>

</div> <!-- Header section -->

<div class = "header-shading">

#### How INTENSE have your alcohol or drug cravings been? <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7651-anchor"> [Item 7651] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8102-anchor">
  <strong>Question ID</strong>: Question 8102
</div>

**Way the question was delivered:** Slider

**Type of data:** numeric

</div> <div class = "anchor">






**Descriptives**
Min = 0, Max = 100, Mean = 9.05, SD = 17.45 



<button 
  onclick="let e = document.getElementById('Question 8102');
           let arrow = document.getElementById('Question 8102_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8102_arrow">▼</span>
</button>

<div id="Question 8102" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram

![](Codebook_files/figure-html/histogram-Slider-Question-8102-Item-7651-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 1045 / 1046

Missing = 1
Min = 0, Max = 1, Mean = 0.01, SD = 0.09
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = 1.13 



#### Screenshot


</div>

</div> <!-- Header section -->

<div class = "header-shading">

#### TODAY, have you felt any... <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7653-anchor"> [Item 7653] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8103-anchor">
  <strong>Question ID</strong>: Question 8103
</div>

**Way the question was delivered:** Informational Fullscreen

**Type of data:** NA

</div> <div class = "anchor">







</div> <!-- Header section -->

<div class = "header-shading">

#### PHYSICAL DISCOMFORT? <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7654-anchor"> [Item 7654] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8104-anchor">
  <strong>Question ID</strong>: Question 8104
</div>

**Way the question was delivered:** Slider

**Type of data:** numeric

</div> <div class = "anchor">






**Descriptives**
Min = 0, Max = 100, Mean = 33.8, SD = 31.17 



<button 
  onclick="let e = document.getElementById('Question 8104');
           let arrow = document.getElementById('Question 8104_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8104_arrow">▼</span>
</button>

<div id="Question 8104" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram

![](Codebook_files/figure-html/histogram-Slider-Question-8104-Item-7654-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 1044 / 1046

Missing = 2
Min = 0, Max = 1, Mean = 0.02, SD = 0.12
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = 1.15 



#### Screenshot


</div>

</div> <!-- Header section -->

<div class = "header-shading">

#### PHYSICAL PAIN? <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7655-anchor"> [Item 7655] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8105-anchor">
  <strong>Question ID</strong>: Question 8105
</div>

**Way the question was delivered:** Slider

**Type of data:** numeric

</div> <div class = "anchor">






**Descriptives**
Min = 0, Max = 100, Mean = 33.03, SD = 31.81 



<button 
  onclick="let e = document.getElementById('Question 8105');
           let arrow = document.getElementById('Question 8105_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8105_arrow">▼</span>
</button>

<div id="Question 8105" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram

![](Codebook_files/figure-html/histogram-Slider-Question-8105-Item-7655-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 1044 / 1046

Missing = 2
Min = 0, Max = 1, Mean = 0.02, SD = 0.12
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = 1.15 



#### Screenshot


</div>

</div> <!-- Header section -->

<div class = "header-shading">

#### TODAY, have you felt...  (Scroll down for all responses) <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7656-anchor"> [Item 7656] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8106-anchor">
  <strong>Question ID</strong>: Question 8106
</div>

**Way the question was delivered:** Multiple Slider

**Type of data:** NA

</div> <div class = "anchor">









</div>

 <div class = "header-shading">

#### SAD?

</div>


<div class = "anchor">






**Descriptives**
Min = 0, max = 100, mean = 25.26, std = 28.08









<button 
  onclick="let e = document.getElementById('multiplesliderQuestion-810649993');
           let arrow = document.getElementById('multiplesliderQuestion-810649993_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="multiplesliderQuestion-810649993_arrow">▼</span>
</button>

<div id="multiplesliderQuestion-810649993" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram






![](Codebook_files/figure-html/multiplesliderQuestion-810649993_histogram-1.png)<!-- -->


#### Missingness



**Missingness Descriptives**

Missing descriptives for Multiple Slider questions have not been implemented yet


</details>



#### Screenshot


</div>

</div>

 <div class = "header-shading">

#### LONELY?

</div>


<div class = "anchor">






**Descriptives**
Min = 0, max = 100, mean = 23.57, std = 27.05









<button 
  onclick="let e = document.getElementById('multiplesliderQuestion-810649987');
           let arrow = document.getElementById('multiplesliderQuestion-810649987_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="multiplesliderQuestion-810649987_arrow">▼</span>
</button>

<div id="multiplesliderQuestion-810649987" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram






![](Codebook_files/figure-html/multiplesliderQuestion-810649987_histogram-1.png)<!-- -->


#### Missingness



**Missingness Descriptives**

Missing descriptives for Multiple Slider questions have not been implemented yet


</details>



#### Screenshot


</div>

</div>

 <div class = "header-shading">

#### IRRITABLE?

</div>


<div class = "anchor">






**Descriptives**
Min = 0, max = 100, mean = 31.09, std = 28.65









<button 
  onclick="let e = document.getElementById('multiplesliderQuestion-810649989');
           let arrow = document.getElementById('multiplesliderQuestion-810649989_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="multiplesliderQuestion-810649989_arrow">▼</span>
</button>

<div id="multiplesliderQuestion-810649989" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram






![](Codebook_files/figure-html/multiplesliderQuestion-810649989_histogram-1.png)<!-- -->


#### Missingness



**Missingness Descriptives**

Missing descriptives for Multiple Slider questions have not been implemented yet


</details>



#### Screenshot


</div>

</div>

 <div class = "header-shading">

#### ANXIOUS?

</div>


<div class = "anchor">






**Descriptives**
Min = 0, max = 100, mean = 35.35, std = 31.42









<button 
  onclick="let e = document.getElementById('multiplesliderQuestion-810649991');
           let arrow = document.getElementById('multiplesliderQuestion-810649991_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="multiplesliderQuestion-810649991_arrow">▼</span>
</button>

<div id="multiplesliderQuestion-810649991" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram






![](Codebook_files/figure-html/multiplesliderQuestion-810649991_histogram-1.png)<!-- -->


#### Missingness



**Missingness Descriptives**

Missing descriptives for Multiple Slider questions have not been implemented yet


</details>



#### Screenshot


</div>

</div>

 <div class = "header-shading">

#### RELAXED?

</div>


<div class = "anchor">






**Descriptives**
Min = 0, max = 100, mean = 55.98, std = 27.85









<button 
  onclick="let e = document.getElementById('multiplesliderQuestion-810649995');
           let arrow = document.getElementById('multiplesliderQuestion-810649995_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="multiplesliderQuestion-810649995_arrow">▼</span>
</button>

<div id="multiplesliderQuestion-810649995" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram






![](Codebook_files/figure-html/multiplesliderQuestion-810649995_histogram-1.png)<!-- -->


#### Missingness



**Missingness Descriptives**

Missing descriptives for Multiple Slider questions have not been implemented yet


</details>



#### Screenshot


</div>

</div>

 <div class = "header-shading">

#### HAPPY?

</div>


<div class = "anchor">






**Descriptives**
Min = 0, max = 100, mean = 66.12, std = 24.99









<button 
  onclick="let e = document.getElementById('multiplesliderQuestion-810649997');
           let arrow = document.getElementById('multiplesliderQuestion-810649997_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="multiplesliderQuestion-810649997_arrow">▼</span>
</button>

<div id="multiplesliderQuestion-810649997" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram






![](Codebook_files/figure-html/multiplesliderQuestion-810649997_histogram-1.png)<!-- -->


#### Missingness



**Missingness Descriptives**

Missing descriptives for Multiple Slider questions have not been implemented yet


</details>



#### Screenshot


</div>

</div>

 <div class = "header-shading">

#### CALM?

</div>


<div class = "anchor">






**Descriptives**
Min = 0, max = 100, mean = 61.49, std = 25.93









<button 
  onclick="let e = document.getElementById('multiplesliderQuestion-810649999');
           let arrow = document.getElementById('multiplesliderQuestion-810649999_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="multiplesliderQuestion-810649999_arrow">▼</span>
</button>

<div id="multiplesliderQuestion-810649999" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram






![](Codebook_files/figure-html/multiplesliderQuestion-810649999_histogram-1.png)<!-- -->


#### Missingness



**Missingness Descriptives**

Missing descriptives for Multiple Slider questions have not been implemented yet


</details>



#### Screenshot


</div>

</div>

 <div class = "header-shading">

#### JOYFUL?

</div>


<div class = "anchor">






**Descriptives**
Min = 0, max = 100, mean = 64.14, std = 27.18









<button 
  onclick="let e = document.getElementById('multiplesliderQuestion-810650001');
           let arrow = document.getElementById('multiplesliderQuestion-810650001_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="multiplesliderQuestion-810650001_arrow">▼</span>
</button>

<div id="multiplesliderQuestion-810650001" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram






![](Codebook_files/figure-html/multiplesliderQuestion-810650001_histogram-1.png)<!-- -->


#### Missingness



**Missingness Descriptives**

Missing descriptives for Multiple Slider questions have not been implemented yet


</details>



#### Screenshot


</div>

</div>


 <!-- Header section -->

<div class = "header-shading">

#### Please think of your experiences throughout THE ENTIRE DAY <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7658-anchor"> [Item 7658] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8107-anchor">
  <strong>Question ID</strong>: Question 8107
</div>

**Way the question was delivered:** Informational Fullscreen

**Type of data:** NA

</div> <div class = "anchor">







</div> <!-- Header section -->

<div class = "header-shading">

#### My day has been...  (Scroll down for all responses) <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7659-anchor"> [Item 7659] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8108-anchor">
  <strong>Question ID</strong>: Question 8108
</div>

**Way the question was delivered:** Multiple Slider

**Type of data:** NA

</div> <div class = "anchor">









</div>

 <div class = "header-shading">

#### MEANINGFUL

</div>


<div class = "anchor">






**Descriptives**
Min = 0, max = 100, mean = 73.08, std = 23.82









<button 
  onclick="let e = document.getElementById('multiplesliderQuestion-810850004');
           let arrow = document.getElementById('multiplesliderQuestion-810850004_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="multiplesliderQuestion-810850004_arrow">▼</span>
</button>

<div id="multiplesliderQuestion-810850004" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram






![](Codebook_files/figure-html/multiplesliderQuestion-810850004_histogram-1.png)<!-- -->


#### Missingness



**Missingness Descriptives**

Missing descriptives for Multiple Slider questions have not been implemented yet


</details>



#### Screenshot


</div>

</div>

 <div class = "header-shading">

#### GRATIFYING

</div>


<div class = "anchor">






**Descriptives**
Min = 0, max = 100, mean = 73.25, std = 25.08









<button 
  onclick="let e = document.getElementById('multiplesliderQuestion-810850006');
           let arrow = document.getElementById('multiplesliderQuestion-810850006_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="multiplesliderQuestion-810850006_arrow">▼</span>
</button>

<div id="multiplesliderQuestion-810850006" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram






![](Codebook_files/figure-html/multiplesliderQuestion-810850006_histogram-1.png)<!-- -->


#### Missingness



**Missingness Descriptives**

Missing descriptives for Multiple Slider questions have not been implemented yet


</details>



#### Screenshot


</div>

</div>

 <div class = "header-shading">

#### PURPOSEFUL

</div>


<div class = "anchor">






**Descriptives**
Min = 0, max = 100, mean = 75.45, std = 23.95









<button 
  onclick="let e = document.getElementById('multiplesliderQuestion-810850008');
           let arrow = document.getElementById('multiplesliderQuestion-810850008_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="multiplesliderQuestion-810850008_arrow">▼</span>
</button>

<div id="multiplesliderQuestion-810850008" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram






![](Codebook_files/figure-html/multiplesliderQuestion-810850008_histogram-1.png)<!-- -->


#### Missingness



**Missingness Descriptives**

Missing descriptives for Multiple Slider questions have not been implemented yet


</details>



#### Screenshot


</div>

</div>

 <div class = "header-shading">

#### SATISFYING

</div>


<div class = "anchor">






**Descriptives**
Min = 0, max = 100, mean = 71.77, std = 26.29









<button 
  onclick="let e = document.getElementById('multiplesliderQuestion-810850010');
           let arrow = document.getElementById('multiplesliderQuestion-810850010_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="multiplesliderQuestion-810850010_arrow">▼</span>
</button>

<div id="multiplesliderQuestion-810850010" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram






![](Codebook_files/figure-html/multiplesliderQuestion-810850010_histogram-1.png)<!-- -->


#### Missingness



**Missingness Descriptives**

Missing descriptives for Multiple Slider questions have not been implemented yet


</details>



#### Screenshot


</div>

</div>


 <!-- Header section -->

<div class = "header-shading">

#### THINKING ABOUT TODAY, I feel like...  (Scroll down for all responses) <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7660-anchor"> [Item 7660] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8109-anchor">
  <strong>Question ID</strong>: Question 8109
</div>

**Way the question was delivered:** Multiple Slider

**Type of data:** NA

</div> <div class = "anchor">









</div>

 <div class = "header-shading">

#### I was committed to my recovery

</div>


<div class = "anchor">






**Descriptives**
Min = 0, max = 100, mean = 85.72, std = 19.92









<button 
  onclick="let e = document.getElementById('multiplesliderQuestion-810950012');
           let arrow = document.getElementById('multiplesliderQuestion-810950012_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="multiplesliderQuestion-810950012_arrow">▼</span>
</button>

<div id="multiplesliderQuestion-810950012" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram






![](Codebook_files/figure-html/multiplesliderQuestion-810950012_histogram-1.png)<!-- -->


#### Missingness



**Missingness Descriptives**

Missing descriptives for Multiple Slider questions have not been implemented yet


</details>



#### Screenshot


</div>

</div>

 <div class = "header-shading">

#### I worked hard on my recovery

</div>


<div class = "anchor">






**Descriptives**
Min = 0, max = 100, mean = 69.79, std = 27.52









<button 
  onclick="let e = document.getElementById('multiplesliderQuestion-810950014');
           let arrow = document.getElementById('multiplesliderQuestion-810950014_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="multiplesliderQuestion-810950014_arrow">▼</span>
</button>

<div id="multiplesliderQuestion-810950014" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram






![](Codebook_files/figure-html/multiplesliderQuestion-810950014_histogram-1.png)<!-- -->


#### Missingness



**Missingness Descriptives**

Missing descriptives for Multiple Slider questions have not been implemented yet


</details>



#### Screenshot


</div>

</div>

 <div class = "header-shading">

#### I kept my recovery central to my day

</div>


<div class = "anchor">






**Descriptives**
Min = 0, max = 100, mean = 74.87, std = 25.52









<button 
  onclick="let e = document.getElementById('multiplesliderQuestion-810950016');
           let arrow = document.getElementById('multiplesliderQuestion-810950016_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="multiplesliderQuestion-810950016_arrow">▼</span>
</button>

<div id="multiplesliderQuestion-810950016" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram






![](Codebook_files/figure-html/multiplesliderQuestion-810950016_histogram-1.png)<!-- -->


#### Missingness



**Missingness Descriptives**

Missing descriptives for Multiple Slider questions have not been implemented yet


</details>



#### Screenshot


</div>

</div>

 <div class = "header-shading">

#### I felt connected to other people in recovery

</div>


<div class = "anchor">






**Descriptives**
Min = 0, max = 100, mean = 69.85, std = 31.42









<button 
  onclick="let e = document.getElementById('multiplesliderQuestion-810950018');
           let arrow = document.getElementById('multiplesliderQuestion-810950018_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="multiplesliderQuestion-810950018_arrow">▼</span>
</button>

<div id="multiplesliderQuestion-810950018" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram






![](Codebook_files/figure-html/multiplesliderQuestion-810950018_histogram-1.png)<!-- -->


#### Missingness



**Missingness Descriptives**

Missing descriptives for Multiple Slider questions have not been implemented yet


</details>



#### Screenshot


</div>

</div>

 <div class = "header-shading">

#### I was grateful to be in recovery

</div>


<div class = "anchor">






**Descriptives**
Min = 0, max = 100, mean = 89.38, std = 17.79









<button 
  onclick="let e = document.getElementById('multiplesliderQuestion-810950020');
           let arrow = document.getElementById('multiplesliderQuestion-810950020_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="multiplesliderQuestion-810950020_arrow">▼</span>
</button>

<div id="multiplesliderQuestion-810950020" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram






![](Codebook_files/figure-html/multiplesliderQuestion-810950020_histogram-1.png)<!-- -->


#### Missingness



**Missingness Descriptives**

Missing descriptives for Multiple Slider questions have not been implemented yet


</details>



#### Screenshot


</div>

</div>

 <div class = "header-shading">

#### I missed my old drug use/drinking social group

</div>


<div class = "anchor">






**Descriptives**
Min = 0, max = 100, mean = 9.3, std = 20.32









<button 
  onclick="let e = document.getElementById('multiplesliderQuestion-810950022');
           let arrow = document.getElementById('multiplesliderQuestion-810950022_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="multiplesliderQuestion-810950022_arrow">▼</span>
</button>

<div id="multiplesliderQuestion-810950022" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram






![](Codebook_files/figure-html/multiplesliderQuestion-810950022_histogram-1.png)<!-- -->


#### Missingness



**Missingness Descriptives**

Missing descriptives for Multiple Slider questions have not been implemented yet


</details>



#### Screenshot


</div>

</div>


 <!-- Header section -->

<div class = "header-shading">

#### When thinking about tomorrow, I think tomorrow will be...  (Scroll down for all responses) <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7661-anchor"> [Item 7661] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8110-anchor">
  <strong>Question ID</strong>: Question 8110
</div>

**Way the question was delivered:** Multiple Slider

**Type of data:** NA

</div> <div class = "anchor">









</div>

 <div class = "header-shading">

#### a STRESSFUL day

</div>


<div class = "anchor">






**Descriptives**
Min = 0, max = 100, mean = 37.12, std = 29.47









<button 
  onclick="let e = document.getElementById('multiplesliderQuestion-811050024');
           let arrow = document.getElementById('multiplesliderQuestion-811050024_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="multiplesliderQuestion-811050024_arrow">▼</span>
</button>

<div id="multiplesliderQuestion-811050024" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram






![](Codebook_files/figure-html/multiplesliderQuestion-811050024_histogram-1.png)<!-- -->


#### Missingness



**Missingness Descriptives**

Missing descriptives for Multiple Slider questions have not been implemented yet


</details>



#### Screenshot


</div>

</div>

 <div class = "header-shading">

#### a POSITIVE day

</div>


<div class = "anchor">






**Descriptives**
Min = 0, max = 100, mean = 75.53, std = 22.61









<button 
  onclick="let e = document.getElementById('multiplesliderQuestion-811050026');
           let arrow = document.getElementById('multiplesliderQuestion-811050026_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="multiplesliderQuestion-811050026_arrow">▼</span>
</button>

<div id="multiplesliderQuestion-811050026" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram






![](Codebook_files/figure-html/multiplesliderQuestion-811050026_histogram-1.png)<!-- -->


#### Missingness



**Missingness Descriptives**

Missing descriptives for Multiple Slider questions have not been implemented yet


</details>



#### Screenshot


</div>

</div>

 <div class = "header-shading">

#### a CHALLENGING day

</div>


<div class = "anchor">






**Descriptives**
Min = 0, max = 100, mean = 47.83, std = 32.22









<button 
  onclick="let e = document.getElementById('multiplesliderQuestion-811050028');
           let arrow = document.getElementById('multiplesliderQuestion-811050028_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="multiplesliderQuestion-811050028_arrow">▼</span>
</button>

<div id="multiplesliderQuestion-811050028" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram






![](Codebook_files/figure-html/multiplesliderQuestion-811050028_histogram-1.png)<!-- -->


#### Missingness



**Missingness Descriptives**

Missing descriptives for Multiple Slider questions have not been implemented yet


</details>



#### Screenshot


</div>

</div>

 <div class = "header-shading">

#### an ENJOYABLE day

</div>


<div class = "anchor">






**Descriptives**
Min = 0, max = 100, mean = 73.79, std = 24.3









<button 
  onclick="let e = document.getElementById('multiplesliderQuestion-811050030');
           let arrow = document.getElementById('multiplesliderQuestion-811050030_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="multiplesliderQuestion-811050030_arrow">▼</span>
</button>

<div id="multiplesliderQuestion-811050030" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram






![](Codebook_files/figure-html/multiplesliderQuestion-811050030_histogram-1.png)<!-- -->


#### Missingness



**Missingness Descriptives**

Missing descriptives for Multiple Slider questions have not been implemented yet


</details>



#### Screenshot


</div>

</div>


 <!-- Header section -->

<div class = "header-shading">

#### Im worried about my ability to... <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7662-anchor"> [Item 7662] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8111-anchor">
  <strong>Question ID</strong>: Question 8111
</div>

**Way the question was delivered:** Informational Fullscreen

**Type of data:** NA

</div> <div class = "anchor">







</div> <!-- Header section -->

<div class = "header-shading">

#### Maintain MY RECOVERY tomorrow <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7663-anchor"> [Item 7663] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8112-anchor">
  <strong>Question ID</strong>: Question 8112
</div>

**Way the question was delivered:** Slider

**Type of data:** numeric

</div> <div class = "anchor">






**Descriptives**
Min = 0, Max = 100, Mean = 12.97, SD = 23.53 



<button 
  onclick="let e = document.getElementById('Question 8112');
           let arrow = document.getElementById('Question 8112_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8112_arrow">▼</span>
</button>

<div id="Question 8112" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram

![](Codebook_files/figure-html/histogram-Slider-Question-8112-Item-7663-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 1043 / 1044

Missing = 1
Min = 0, Max = 1, Mean = 0.01, SD = 0.09
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = 1.13 



#### Screenshot


</div>

</div> <!-- Header section -->

<div class = "header-shading">

#### Maintain MY GENERAL WELLBEING tomorrow <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7664-anchor"> [Item 7664] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8113-anchor">
  <strong>Question ID</strong>: Question 8113
</div>

**Way the question was delivered:** Slider

**Type of data:** numeric

</div> <div class = "anchor">






**Descriptives**
Min = 0, Max = 100, Mean = 25.1, SD = 30.65 



<button 
  onclick="let e = document.getElementById('Question 8113');
           let arrow = document.getElementById('Question 8113_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8113_arrow">▼</span>
</button>

<div id="Question 8113" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram

![](Codebook_files/figure-html/histogram-Slider-Question-8113-Item-7664-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 1042 / 1044

Missing = 2
Min = 0, Max = 1, Mean = 0.02, SD = 0.12
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = 1.15 



#### Screenshot


</div>

</div> <!-- Header section -->

<div class = "header-shading">

#### Did you interact in-person, or by phone, text, or social media with your child(ren) today? <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7690-anchor"> [Item 7690] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8183-anchor">
  <strong>Question ID</strong>: Question 8183
</div>

**Way the question was delivered:** Multiple Choice

**Type of data:** integer

</div> 
<div class = "anchor">




<button 
  onclick="let e = document.getElementById('Question 8183');
           let arrow = document.getElementById('Question 8183_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8183_arrow">▼</span>
</button>

<div id="Question 8183" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Frequency Table

<table class="table" style="color: black; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> Value </th>
   <th style="text-align:left;"> Label </th>
   <th style="text-align:left;"> Counts </th>
   <th style="text-align:left;"> Percentages </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:left;"> I DID NOT interact with kid or kids today </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 78 </td>
   <td style="text-align:left;"> 14% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2 </td>
   <td style="text-align:left;"> I DID interact with kid or kids today </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 481 </td>
   <td style="text-align:left;"> 86% </td>
  </tr>
</tbody>
</table>


#### Barplot

![](Codebook_files/figure-html/barplot-Multiple-Choice-Question-8183-Item-7690-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 559 / 559

Missing = 0
Min = 0, Max = 0, Mean = 0, SD = 0
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = NaN 


#### Screenshot



</div>


</div> <!-- Header section -->

<div class = "header-shading">

#### Please check off all the ways in which you interacted with your kid or kids today:  (Scroll down for all responses) <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7667-anchor"> [Item 7667] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8648-anchor">
  <strong>Question ID</strong>: Question 8648
</div>

**Way the question was delivered:** Multiple Select

**Type of data:** integer

</div> 
<div class = "anchor">




<button 
  onclick="let e = document.getElementById('Question 8648');
           let arrow = document.getElementById('Question 8648_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8648_arrow">▼</span>
</button>

<div id="Question 8648" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Frequency Table

<table class="table" style="color: black; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> Value </th>
   <th style="text-align:left;"> Label </th>
   <th style="text-align:left;"> Counts </th>
   <th style="text-align:left;"> Percentages </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:left;"> Phone call </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 114 </td>
   <td style="text-align:left;"> 13.4% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2 </td>
   <td style="text-align:left;"> Voice message </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 26 </td>
   <td style="text-align:left;"> 3.1% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 3 </td>
   <td style="text-align:left;"> Video call </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 52 </td>
   <td style="text-align:left;"> 6.1% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 4 </td>
   <td style="text-align:left;"> Text message </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 182 </td>
   <td style="text-align:left;"> 21.4% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 5 </td>
   <td style="text-align:left;"> In-person </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 396 </td>
   <td style="text-align:left;"> 46.6% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 6 </td>
   <td style="text-align:left;"> Posting to social media about kid </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 23 </td>
   <td style="text-align:left;"> 2.7% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 7 </td>
   <td style="text-align:left;"> Responding to a kid's post </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 7 </td>
   <td style="text-align:left;"> 0.8% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 8 </td>
   <td style="text-align:left;"> Messaging through facebook or other social media </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 38 </td>
   <td style="text-align:left;"> 4.5% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 9 </td>
   <td style="text-align:left;"> Other </td>
   <td style="text-align:left;color: darkgreen !important;"> N = 11 </td>
   <td style="text-align:left;"> 1.3% </td>
  </tr>
</tbody>
</table>


#### Barplot

![](Codebook_files/figure-html/barplot-Multiple-Select-Question-8648-Item-7667-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 479 / 479

Missing = 0
Min = 0, Max = 0, Mean = 0, SD = 0
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = NaN 


#### Screenshot



</div>


</div> <!-- Header section -->

<div class = "header-shading">

#### Thinking of all your interactions with your child(ren) today --OVERALL how POSITIVE were they? <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7669-anchor"> [Item 7669] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8117-anchor">
  <strong>Question ID</strong>: Question 8117
</div>

**Way the question was delivered:** Slider

**Type of data:** numeric

</div> <div class = "anchor">






**Descriptives**
Min = 0, Max = 100, Mean = 85.65, SD = 18.99 



<button 
  onclick="let e = document.getElementById('Question 8117');
           let arrow = document.getElementById('Question 8117_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8117_arrow">▼</span>
</button>

<div id="Question 8117" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram

![](Codebook_files/figure-html/histogram-Slider-Question-8117-Item-7669-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 484 / 484

Missing = 0
Min = 0, Max = 0, Mean = 0, SD = 0
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = NaN 



#### Screenshot


</div>

</div> <!-- Header section -->

<div class = "header-shading">

#### Thinking of all your interactions with your child(ren) today --OVERALL how NEGATIVE were they? <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7670-anchor"> [Item 7670] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8118-anchor">
  <strong>Question ID</strong>: Question 8118
</div>

**Way the question was delivered:** Slider

**Type of data:** numeric

</div> <div class = "anchor">






**Descriptives**
Min = 0, Max = 100, Mean = 14.48, SD = 20.9 



<button 
  onclick="let e = document.getElementById('Question 8118');
           let arrow = document.getElementById('Question 8118_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8118_arrow">▼</span>
</button>

<div id="Question 8118" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram

![](Codebook_files/figure-html/histogram-Slider-Question-8118-Item-7670-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 483 / 484

Missing = 1
Min = 0, Max = 1, Mean = 0.02, SD = 0.12
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = 1.17 



#### Screenshot


</div>

</div> <!-- Header section -->

<div class = "header-shading">

#### Thinking of all your interactions with your child(ren) today --OVERALL how FULFILLING were they? <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7671-anchor"> [Item 7671] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8119-anchor">
  <strong>Question ID</strong>: Question 8119
</div>

**Way the question was delivered:** Slider

**Type of data:** numeric

</div> <div class = "anchor">






**Descriptives**
Min = 0, Max = 100, Mean = 84.39, SD = 19.43 



<button 
  onclick="let e = document.getElementById('Question 8119');
           let arrow = document.getElementById('Question 8119_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8119_arrow">▼</span>
</button>

<div id="Question 8119" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram

![](Codebook_files/figure-html/histogram-Slider-Question-8119-Item-7671-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 483 / 484

Missing = 1
Min = 0, Max = 1, Mean = 0.02, SD = 0.12
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = 1.17 



#### Screenshot


</div>

</div> <!-- Header section -->

<div class = "header-shading">

#### Thinking of all your interactions with your child(ren) today --OVERALL how FRUSTRATING were they? <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7672-anchor"> [Item 7672] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8120-anchor">
  <strong>Question ID</strong>: Question 8120
</div>

**Way the question was delivered:** Slider

**Type of data:** numeric

</div> <div class = "anchor">






**Descriptives**
Min = 0, Max = 100, Mean = 22.74, SD = 27.03 



<button 
  onclick="let e = document.getElementById('Question 8120');
           let arrow = document.getElementById('Question 8120_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8120_arrow">▼</span>
</button>

<div id="Question 8120" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Histogram

![](Codebook_files/figure-html/histogram-Slider-Question-8120-Item-7672-1.png)<!-- -->


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 483 / 484

Missing = 1
Min = 0, Max = 1, Mean = 0.02, SD = 0.12
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = 1.17 



#### Screenshot


</div>

</div> <!-- Header section -->

<div class = "header-shading">

#### End Block <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7674-anchor"> [Item 7674] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8121-anchor">
  <strong>Question ID</strong>: Question 8121
</div>

**Way the question was delivered:** End Block

**Type of data:** NA

</div>  <!-- Header section -->

<div class = "header-shading">

#### OPTIONAL DAILY REFLECTION: Describe what was challenging and/or good about your day and how you feel about it (about recovery or not):  Up to around 100 words <br>

<div style="font-weight: bold; color: #2a5caa; margin-top: -0.7em; margin-bottom: 1em;">
  <a href="#Item 7676-anchor"> [Item 7676] </a>
</div>


</div>



<!-- Body -->


<div class = "anchor">

<div id="Question 8122-anchor">
  <strong>Question ID</strong>: Question 8122
</div>

**Way the question was delivered:** Free Response

**Type of data:** character

</div> <div class = "anchor">






<button 
  onclick="let e = document.getElementById('Question 8122');
           let arrow = document.getElementById('Question 8122_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="Question 8122_arrow">▼</span>
</button>

<div id="Question 8122" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}


#### Missingness

**Missingness Descriptives**

Answered / Delivered = 797 / 1041

Missing = 244
Min = 0, Max = 11, Mean = 1.85, SD = 2.52
(Descriptives are rounded to 2 decimals)

Missingness Intraclass Correlation (ICC) = 1.07 


#### Screenshot



</div>


</div> 
### Block: Item 7677 
### Block: Item 7615 
### Block: Item 7636 
### Block: Item 7635 
### Block: Item 7613 
### Block: Item 7637 
### Block: Item 7630 
### Block: Item 7647 
### Block: Item 7648 
### Block: Item 7657 
### Block: Item 7665 
### Block: Item 7675 
### Block: Item 7673


