---
title: "Recovery Community Center Project Mock Codebook"
author: "Kile, O. E., & Brick, R. T."
date: "Codebook Generated `r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc-depth: 5
    css: styles.css
    includes:
      before_body: logo.html
---


```{r Highest-Level-Template-Chunk, include = FALSE}
library(knitr)

#############################
# Knit expand provenance
#############################

# 1.) Highest Level Template.Rmd

# 2.) Codebook.Rmd

# 3.) DataTypes/question_type_no_space.Rmd

#############################
#############################
#############################


#Title Page
title <- "Recovery General Project"
authors <- "Timothy R. Brick, Ethan O. Kile"
funding <- "This work has been funded by Pennsylvania State University, Department of Human Development and Family Studies"






#Abstract page
abstract <- "This study looked to review the current EMA reporting standards for complex data types as to assess areas in need of improvement. This work also looked to develop a reference implementation that can be used to help EMA researchers adhere to our proposed gold standard EMA reporting standard. The mock codebook has been generated from data provided by Hobart H. Cleveland from his Recovery General Project. This work has been conducted by Ethan O. Kile & Timothy R. Brick with the help of the Wear-IT team at the Department of Human Development and Family Studies at Pennsylvania State University."


##Brief description of study 
summary <- "This study found that current EMA reporting standards, especially in regard to complex study designs, are lacking in areas of reporting user interface elements, missingness, skip logic and adaptive triggers. Additionally, this study has also found that it is possible to streamline the reporting of essential para and meta data elements through automated codebook generation as to ensure that data is findable, accessible, interoperable and reusable (Gilmore et al., 2018)."



#############
# New data version
#############


# Load survey_data
thisData <- read.csv("processedData/surveyCombined.csv")

# Load block_map
blockMap <- read.csv("processedData/questionMap.csv")

# Load survey_info
#surveyInfo <- read.csv("loadedData/survey_info.csv")

# Load responseMap
responseKey <- read.csv("processedData/responseMap.csv")

 


#Variable List
#Load survey_data
#thisData <- read.csv("loadedData/survey_data.csv")

#Load block_map
#blockMap <- read.csv("loadedData/block_map.csv")

#Load survey_info
#surveyInfo <- read.csv("loadedData/survey_info.csv")

#Load responseMap
#responseKey <- read.csv("loadedData/responseMap.csv")


######################################################################################
## Take out practice questions (this will need to go into the processing of the data)
######################################################################################

thisData <- thisData[thisData$Survey.Name == "Daily Diary",]



blockMap <- blockMap[!grepl("Practice", blockMap$Survey, ignore.case = TRUE), ]

# Not sure where these are coming from, they are repeats but not marked practice
#####################
### Processing RCC
####################
#blockMap <- blockMap[!grepl("Item 6026", blockMap$Survey), ]
#blockMap <- blockMap[-1, ]
#blockMap <- blockMap[-(47:51), ]


###############

### Processing RG

#############
blockMap <- blockMap[!is.na(blockMap$Question.Type.Display.Name), ]


blockMap <- blockMap[!grepl("Unit Scale Slider", blockMap$Question.Type.Display.Name), ]
blockMap <- blockMap[!grepl("Time Scale Slider", blockMap$Question.Type.Display.Name), ]
blockMap$Question.Type.Display.Name[blockMap$Question.Type.Display.Name == "Reducing Slider"] <- "Slider"

# Talk to tim about this possible
blockMap$Question.Text <- gsub("<[^>]+>", "", blockMap$Question.Text)
blockMap$Question.Text <- gsub('[\"“”‘’\']', '', blockMap$Question.Text)




```


```{r, include = FALSE}
###############
## This is a check for unsupported data types which prompts the user to answer yes or no if they want to continue, 
## if no, cancel the knit, if yes, continue knit and drop those questions from the data processing
###############

# Check unique data types
data_types <- unique(blockMap$Question.Type.Display.Name)

unsupported_data_types <- character()

# Index data types
for (data_type in data_types) {
  
  # Clean out spaces
  data_type_no_space <- gsub(" ", "", data_type)
  # Check for rmd files
  if (!file.exists(paste0("DataTypes/", data_type_no_space, ".Rmd"))) {
    # If does not exists add to vector
    unsupported_data_types <- c(unsupported_data_types, data_type)
  }
  
}

# If there are any unsupported data types....
if (length(unsupported_data_types) > 0) {
  
  # Paste error msg and display unsupported types
  cat("The following question types are not supported by this version of the Real Time Science lab codebook generation tool:\n")
  cat(paste("-", unsupported_data_types), sep = "\n")
  
  repeat {
    
    # Prompt user how to continue
    response <- readline(prompt = "Questions with unsupported data types will be dropped. Do you want to continue knitting? (y/n): ")
    
    # If yes, continue knit call
    if (tolower(response) == "y") {
      cat("Continuing knit call... \n")
      break
      
    # If no, stop knit call
    } else if (tolower(response) == "n") {
      stop("Stopping knit call")
    
    # If invalid return to top of call  
    } else {
      cat("Error, wrong response input, please respond 'y' or 'n'\n")
    }
  }
}



# Drop unsupported data types
blockMap <- blockMap[!(blockMap$Question.Type.Display.Name %in% unsupported_data_types), ]




###############

### Processing FamBes

#############
#blockMap$Question.Text <- gsub("<[^>]+>", "", blockMap$Question.Text)
#blockMap$Question.Text <- gsub('[\"“”‘’\']', '', blockMap$Question.Text)
#blockMap <- blockMap[!grepl("Unit Scale Slider", blockMap$Question.Type.Display.Name), ]
#blockMap <- blockMap[!grepl("Time Scale Slider", blockMap$Question.Type.Display.Name), ]
#blockMap$Question.Type.Display.Name[blockMap$Question.Type.Display.Name == "Reducing Slider"] <- "Slider"



```


```{r Highest-Knit-Expand, include = FALSE}
out <- knit_expand("Codebook.Rmd")

```


`r knit(text=out)`

