<div class = "header-shading">

#### {{question_text}}

</div>


<div class = "anchor">



```{r {{chunk_label}}_descriptives, eval = params$descriptives, echo = FALSE, results = 'asis'}
#########################
# Descriptives
#########################


# Grab basic descriptives
minimum_value <- round(min({{thisVar}}, na.rm = TRUE), 2)
maximum_value <- round(max({{thisVar}}, na.rm = TRUE), 2)
mean_value <- round(mean({{thisVar}}, na.rm = TRUE), 2)
std_value <- round(sd({{thisVar}}, na.rm = TRUE), 2)

  # Create descriptives message
  msg <- paste0(
    "**Descriptives**\n",
    "Min = ", minimum_value, ", ",
    "Max = ", maximum_value, ", ",
    "Mean = ", mean_value, ", ",
    "SD = ", std_value
  )

  # Cat msg
  cat(msg, "\n")

```






```{r {{chunk_label}}_library, include = FALSE}
# Library packages
library(kableExtra)
library(ggplot2)
```




<button 
  onclick="let e = document.getElementById('{{chunk_label}}');
           let arrow = document.getElementById('{{chunk_label}}_arrow');
           e.style.display = e.style.display === 'none' ? 'block' : 'none';
           arrow.textContent = e.style.display === 'none' ? '▼' : '▲';"
  style="background: none; border: none; padding: 0; font-weight: bold; font-size: 18px; color: #2a5caa; cursor: pointer;">
Click to view visuals <span id="{{chunk_label}}_arrow">▼</span>
</button>

<div id="{{chunk_label}}" style="display: none;">


<!-- TOC-IGNORE-BEGIN -->

### Descriptives {.tabset}









```{r {{chunk_label}}_histogram, eval = params$histogram, echo = FALSE, results = 'asis'}

cat("#### Histogram\n\n")
#################
# This is a basic histogram for continous data
######################
hist({{thisVar}}, main = "Histogram", col ="#619CFF", border = "black", xlab = "0 - 100 Slider", prob = TRUE)

# This line + prob = TRUE arg draws density plot over histogram
lines(density({{thisVar}}, na.rm = TRUE), col="blue", lwd=2)


```




```{r {{chunk_label}}_missingness, eval = params$missingnessPage, echo = FALSE, results = 'asis'}
cat("#### Missingness\n\n")

cat("**Missingness Descriptives** \n\n

Missing descriptives for Multiple Slider questions have not been implemented yet")
```




</details>



```{r screenshot-{{chunk_label}}, eval = params$screenshot, echo = FALSE, results = 'asis'}
cat("#### Screenshots")
displayScreenshot(id = "{{item_id}}", screenshotDir = screenshotDir)
```



</div>

</div>


